// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/grid"
	"github.com/shopspring/decimal"
)

// GridCreate is the builder for creating a Grid entity.
type GridCreate struct {
	config
	mutation *GridMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (gc *GridCreate) SetCreateTime(t time.Time) *GridCreate {
	gc.mutation.SetCreateTime(t)
	return gc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (gc *GridCreate) SetNillableCreateTime(t *time.Time) *GridCreate {
	if t != nil {
		gc.SetCreateTime(*t)
	}
	return gc
}

// SetUpdateTime sets the "update_time" field.
func (gc *GridCreate) SetUpdateTime(t time.Time) *GridCreate {
	gc.mutation.SetUpdateTime(t)
	return gc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (gc *GridCreate) SetNillableUpdateTime(t *time.Time) *GridCreate {
	if t != nil {
		gc.SetUpdateTime(*t)
	}
	return gc
}

// SetGUID sets the "guid" field.
func (gc *GridCreate) SetGUID(s string) *GridCreate {
	gc.mutation.SetGUID(s)
	return gc
}

// SetAccount sets the "account" field.
func (gc *GridCreate) SetAccount(s string) *GridCreate {
	gc.mutation.SetAccount(s)
	return gc
}

// SetToken sets the "token" field.
func (gc *GridCreate) SetToken(s string) *GridCreate {
	gc.mutation.SetToken(s)
	return gc
}

// SetSymbol sets the "symbol" field.
func (gc *GridCreate) SetSymbol(s string) *GridCreate {
	gc.mutation.SetSymbol(s)
	return gc
}

// SetStrategyId sets the "strategyId" field.
func (gc *GridCreate) SetStrategyId(s string) *GridCreate {
	gc.mutation.SetStrategyId(s)
	return gc
}

// SetGridNumber sets the "gridNumber" field.
func (gc *GridCreate) SetGridNumber(i int) *GridCreate {
	gc.mutation.SetGridNumber(i)
	return gc
}

// SetOrderPrice sets the "orderPrice" field.
func (gc *GridCreate) SetOrderPrice(d decimal.Decimal) *GridCreate {
	gc.mutation.SetOrderPrice(d)
	return gc
}

// SetFinalPrice sets the "finalPrice" field.
func (gc *GridCreate) SetFinalPrice(d decimal.Decimal) *GridCreate {
	gc.mutation.SetFinalPrice(d)
	return gc
}

// SetAmount sets the "amount" field.
func (gc *GridCreate) SetAmount(d decimal.Decimal) *GridCreate {
	gc.mutation.SetAmount(d)
	return gc
}

// SetQuantity sets the "quantity" field.
func (gc *GridCreate) SetQuantity(d decimal.Decimal) *GridCreate {
	gc.mutation.SetQuantity(d)
	return gc
}

// SetStatus sets the "status" field.
func (gc *GridCreate) SetStatus(gr grid.Status) *GridCreate {
	gc.mutation.SetStatus(gr)
	return gc
}

// Mutation returns the GridMutation object of the builder.
func (gc *GridCreate) Mutation() *GridMutation {
	return gc.mutation
}

// Save creates the Grid in the database.
func (gc *GridCreate) Save(ctx context.Context) (*Grid, error) {
	gc.defaults()
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GridCreate) SaveX(ctx context.Context) *Grid {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GridCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GridCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GridCreate) defaults() {
	if _, ok := gc.mutation.CreateTime(); !ok {
		v := grid.DefaultCreateTime()
		gc.mutation.SetCreateTime(v)
	}
	if _, ok := gc.mutation.UpdateTime(); !ok {
		v := grid.DefaultUpdateTime()
		gc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GridCreate) check() error {
	if _, ok := gc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Grid.create_time"`)}
	}
	if _, ok := gc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Grid.update_time"`)}
	}
	if _, ok := gc.mutation.GUID(); !ok {
		return &ValidationError{Name: "guid", err: errors.New(`ent: missing required field "Grid.guid"`)}
	}
	if v, ok := gc.mutation.GUID(); ok {
		if err := grid.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Grid.guid": %w`, err)}
		}
	}
	if _, ok := gc.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "Grid.account"`)}
	}
	if v, ok := gc.mutation.Account(); ok {
		if err := grid.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Grid.account": %w`, err)}
		}
	}
	if _, ok := gc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Grid.token"`)}
	}
	if v, ok := gc.mutation.Token(); ok {
		if err := grid.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Grid.token": %w`, err)}
		}
	}
	if _, ok := gc.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "Grid.symbol"`)}
	}
	if v, ok := gc.mutation.Symbol(); ok {
		if err := grid.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Grid.symbol": %w`, err)}
		}
	}
	if _, ok := gc.mutation.StrategyId(); !ok {
		return &ValidationError{Name: "strategyId", err: errors.New(`ent: missing required field "Grid.strategyId"`)}
	}
	if v, ok := gc.mutation.StrategyId(); ok {
		if err := grid.StrategyIdValidator(v); err != nil {
			return &ValidationError{Name: "strategyId", err: fmt.Errorf(`ent: validator failed for field "Grid.strategyId": %w`, err)}
		}
	}
	if _, ok := gc.mutation.GridNumber(); !ok {
		return &ValidationError{Name: "gridNumber", err: errors.New(`ent: missing required field "Grid.gridNumber"`)}
	}
	if v, ok := gc.mutation.GridNumber(); ok {
		if err := grid.GridNumberValidator(v); err != nil {
			return &ValidationError{Name: "gridNumber", err: fmt.Errorf(`ent: validator failed for field "Grid.gridNumber": %w`, err)}
		}
	}
	if _, ok := gc.mutation.OrderPrice(); !ok {
		return &ValidationError{Name: "orderPrice", err: errors.New(`ent: missing required field "Grid.orderPrice"`)}
	}
	if _, ok := gc.mutation.FinalPrice(); !ok {
		return &ValidationError{Name: "finalPrice", err: errors.New(`ent: missing required field "Grid.finalPrice"`)}
	}
	if _, ok := gc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Grid.amount"`)}
	}
	if _, ok := gc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Grid.quantity"`)}
	}
	if _, ok := gc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Grid.status"`)}
	}
	if v, ok := gc.mutation.Status(); ok {
		if err := grid.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Grid.status": %w`, err)}
		}
	}
	return nil
}

func (gc *GridCreate) sqlSave(ctx context.Context) (*Grid, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GridCreate) createSpec() (*Grid, *sqlgraph.CreateSpec) {
	var (
		_node = &Grid{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(grid.Table, sqlgraph.NewFieldSpec(grid.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.CreateTime(); ok {
		_spec.SetField(grid.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := gc.mutation.UpdateTime(); ok {
		_spec.SetField(grid.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := gc.mutation.GUID(); ok {
		_spec.SetField(grid.FieldGUID, field.TypeString, value)
		_node.GUID = value
	}
	if value, ok := gc.mutation.Account(); ok {
		_spec.SetField(grid.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := gc.mutation.Token(); ok {
		_spec.SetField(grid.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := gc.mutation.Symbol(); ok {
		_spec.SetField(grid.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := gc.mutation.StrategyId(); ok {
		_spec.SetField(grid.FieldStrategyId, field.TypeString, value)
		_node.StrategyId = value
	}
	if value, ok := gc.mutation.GridNumber(); ok {
		_spec.SetField(grid.FieldGridNumber, field.TypeInt, value)
		_node.GridNumber = value
	}
	if value, ok := gc.mutation.OrderPrice(); ok {
		_spec.SetField(grid.FieldOrderPrice, field.TypeString, value)
		_node.OrderPrice = value
	}
	if value, ok := gc.mutation.FinalPrice(); ok {
		_spec.SetField(grid.FieldFinalPrice, field.TypeString, value)
		_node.FinalPrice = value
	}
	if value, ok := gc.mutation.Amount(); ok {
		_spec.SetField(grid.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := gc.mutation.Quantity(); ok {
		_spec.SetField(grid.FieldQuantity, field.TypeString, value)
		_node.Quantity = value
	}
	if value, ok := gc.mutation.Status(); ok {
		_spec.SetField(grid.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// GridCreateBulk is the builder for creating many Grid entities in bulk.
type GridCreateBulk struct {
	config
	err      error
	builders []*GridCreate
}

// Save creates the Grid entities in the database.
func (gcb *GridCreateBulk) Save(ctx context.Context) ([]*Grid, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Grid, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GridMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GridCreateBulk) SaveX(ctx context.Context) []*Grid {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GridCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GridCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
