// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/order"
	"github.com/shopspring/decimal"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (oc *OrderCreate) SetCreateTime(t time.Time) *OrderCreate {
	oc.mutation.SetCreateTime(t)
	return oc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (oc *OrderCreate) SetNillableCreateTime(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetCreateTime(*t)
	}
	return oc
}

// SetUpdateTime sets the "update_time" field.
func (oc *OrderCreate) SetUpdateTime(t time.Time) *OrderCreate {
	oc.mutation.SetUpdateTime(t)
	return oc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (oc *OrderCreate) SetNillableUpdateTime(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetUpdateTime(*t)
	}
	return oc
}

// SetAccount sets the "account" field.
func (oc *OrderCreate) SetAccount(s string) *OrderCreate {
	oc.mutation.SetAccount(s)
	return oc
}

// SetToken sets the "token" field.
func (oc *OrderCreate) SetToken(s string) *OrderCreate {
	oc.mutation.SetToken(s)
	return oc
}

// SetSymbol sets the "symbol" field.
func (oc *OrderCreate) SetSymbol(s string) *OrderCreate {
	oc.mutation.SetSymbol(s)
	return oc
}

// SetGridId sets the "gridId" field.
func (oc *OrderCreate) SetGridId(s string) *OrderCreate {
	oc.mutation.SetGridId(s)
	return oc
}

// SetNillableGridId sets the "gridId" field if the given value is not nil.
func (oc *OrderCreate) SetNillableGridId(s *string) *OrderCreate {
	if s != nil {
		oc.SetGridId(*s)
	}
	return oc
}

// SetGridNumber sets the "gridNumber" field.
func (oc *OrderCreate) SetGridNumber(i int) *OrderCreate {
	oc.mutation.SetGridNumber(i)
	return oc
}

// SetNillableGridNumber sets the "gridNumber" field if the given value is not nil.
func (oc *OrderCreate) SetNillableGridNumber(i *int) *OrderCreate {
	if i != nil {
		oc.SetGridNumber(*i)
	}
	return oc
}

// SetGridBuyCost sets the "gridBuyCost" field.
func (oc *OrderCreate) SetGridBuyCost(d decimal.Decimal) *OrderCreate {
	oc.mutation.SetGridBuyCost(d)
	return oc
}

// SetNillableGridBuyCost sets the "gridBuyCost" field if the given value is not nil.
func (oc *OrderCreate) SetNillableGridBuyCost(d *decimal.Decimal) *OrderCreate {
	if d != nil {
		oc.SetGridBuyCost(*d)
	}
	return oc
}

// SetStrategyId sets the "strategyId" field.
func (oc *OrderCreate) SetStrategyId(s string) *OrderCreate {
	oc.mutation.SetStrategyId(s)
	return oc
}

// SetType sets the "type" field.
func (oc *OrderCreate) SetType(o order.Type) *OrderCreate {
	oc.mutation.SetType(o)
	return oc
}

// SetPrice sets the "price" field.
func (oc *OrderCreate) SetPrice(d decimal.Decimal) *OrderCreate {
	oc.mutation.SetPrice(d)
	return oc
}

// SetFinalPrice sets the "finalPrice" field.
func (oc *OrderCreate) SetFinalPrice(d decimal.Decimal) *OrderCreate {
	oc.mutation.SetFinalPrice(d)
	return oc
}

// SetInAmount sets the "inAmount" field.
func (oc *OrderCreate) SetInAmount(d decimal.Decimal) *OrderCreate {
	oc.mutation.SetInAmount(d)
	return oc
}

// SetOutAmount sets the "outAmount" field.
func (oc *OrderCreate) SetOutAmount(d decimal.Decimal) *OrderCreate {
	oc.mutation.SetOutAmount(d)
	return oc
}

// SetStatus sets the "status" field.
func (oc *OrderCreate) SetStatus(o order.Status) *OrderCreate {
	oc.mutation.SetStatus(o)
	return oc
}

// SetTxHash sets the "txHash" field.
func (oc *OrderCreate) SetTxHash(s string) *OrderCreate {
	oc.mutation.SetTxHash(s)
	return oc
}

// SetReason sets the "reason" field.
func (oc *OrderCreate) SetReason(s string) *OrderCreate {
	oc.mutation.SetReason(s)
	return oc
}

// SetProfit sets the "profit" field.
func (oc *OrderCreate) SetProfit(d decimal.Decimal) *OrderCreate {
	oc.mutation.SetProfit(d)
	return oc
}

// SetNillableProfit sets the "profit" field if the given value is not nil.
func (oc *OrderCreate) SetNillableProfit(d *decimal.Decimal) *OrderCreate {
	if d != nil {
		oc.SetProfit(*d)
	}
	return oc
}

// Mutation returns the OrderMutation object of the builder.
func (oc *OrderCreate) Mutation() *OrderMutation {
	return oc.mutation
}

// Save creates the Order in the database.
func (oc *OrderCreate) Save(ctx context.Context) (*Order, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OrderCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OrderCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OrderCreate) defaults() {
	if _, ok := oc.mutation.CreateTime(); !ok {
		v := order.DefaultCreateTime()
		oc.mutation.SetCreateTime(v)
	}
	if _, ok := oc.mutation.UpdateTime(); !ok {
		v := order.DefaultUpdateTime()
		oc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OrderCreate) check() error {
	if _, ok := oc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Order.create_time"`)}
	}
	if _, ok := oc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Order.update_time"`)}
	}
	if _, ok := oc.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "Order.account"`)}
	}
	if v, ok := oc.mutation.Account(); ok {
		if err := order.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Order.account": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Order.token"`)}
	}
	if v, ok := oc.mutation.Token(); ok {
		if err := order.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Order.token": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "Order.symbol"`)}
	}
	if v, ok := oc.mutation.Symbol(); ok {
		if err := order.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Order.symbol": %w`, err)}
		}
	}
	if v, ok := oc.mutation.GridId(); ok {
		if err := order.GridIdValidator(v); err != nil {
			return &ValidationError{Name: "gridId", err: fmt.Errorf(`ent: validator failed for field "Order.gridId": %w`, err)}
		}
	}
	if _, ok := oc.mutation.StrategyId(); !ok {
		return &ValidationError{Name: "strategyId", err: errors.New(`ent: missing required field "Order.strategyId"`)}
	}
	if v, ok := oc.mutation.StrategyId(); ok {
		if err := order.StrategyIdValidator(v); err != nil {
			return &ValidationError{Name: "strategyId", err: fmt.Errorf(`ent: validator failed for field "Order.strategyId": %w`, err)}
		}
	}
	if _, ok := oc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Order.type"`)}
	}
	if v, ok := oc.mutation.GetType(); ok {
		if err := order.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Order.type": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Order.price"`)}
	}
	if _, ok := oc.mutation.FinalPrice(); !ok {
		return &ValidationError{Name: "finalPrice", err: errors.New(`ent: missing required field "Order.finalPrice"`)}
	}
	if _, ok := oc.mutation.InAmount(); !ok {
		return &ValidationError{Name: "inAmount", err: errors.New(`ent: missing required field "Order.inAmount"`)}
	}
	if _, ok := oc.mutation.OutAmount(); !ok {
		return &ValidationError{Name: "outAmount", err: errors.New(`ent: missing required field "Order.outAmount"`)}
	}
	if _, ok := oc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := oc.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := oc.mutation.TxHash(); !ok {
		return &ValidationError{Name: "txHash", err: errors.New(`ent: missing required field "Order.txHash"`)}
	}
	if v, ok := oc.mutation.TxHash(); ok {
		if err := order.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "txHash", err: fmt.Errorf(`ent: validator failed for field "Order.txHash": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Order.reason"`)}
	}
	if v, ok := oc.mutation.Reason(); ok {
		if err := order.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Order.reason": %w`, err)}
		}
	}
	return nil
}

func (oc *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	)
	if value, ok := oc.mutation.CreateTime(); ok {
		_spec.SetField(order.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := oc.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := oc.mutation.Account(); ok {
		_spec.SetField(order.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := oc.mutation.Token(); ok {
		_spec.SetField(order.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := oc.mutation.Symbol(); ok {
		_spec.SetField(order.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := oc.mutation.GridId(); ok {
		_spec.SetField(order.FieldGridId, field.TypeString, value)
		_node.GridId = &value
	}
	if value, ok := oc.mutation.GridNumber(); ok {
		_spec.SetField(order.FieldGridNumber, field.TypeInt, value)
		_node.GridNumber = &value
	}
	if value, ok := oc.mutation.GridBuyCost(); ok {
		_spec.SetField(order.FieldGridBuyCost, field.TypeString, value)
		_node.GridBuyCost = &value
	}
	if value, ok := oc.mutation.StrategyId(); ok {
		_spec.SetField(order.FieldStrategyId, field.TypeString, value)
		_node.StrategyId = value
	}
	if value, ok := oc.mutation.GetType(); ok {
		_spec.SetField(order.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := oc.mutation.Price(); ok {
		_spec.SetField(order.FieldPrice, field.TypeString, value)
		_node.Price = value
	}
	if value, ok := oc.mutation.FinalPrice(); ok {
		_spec.SetField(order.FieldFinalPrice, field.TypeString, value)
		_node.FinalPrice = value
	}
	if value, ok := oc.mutation.InAmount(); ok {
		_spec.SetField(order.FieldInAmount, field.TypeString, value)
		_node.InAmount = value
	}
	if value, ok := oc.mutation.OutAmount(); ok {
		_spec.SetField(order.FieldOutAmount, field.TypeString, value)
		_node.OutAmount = value
	}
	if value, ok := oc.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := oc.mutation.TxHash(); ok {
		_spec.SetField(order.FieldTxHash, field.TypeString, value)
		_node.TxHash = value
	}
	if value, ok := oc.mutation.Reason(); ok {
		_spec.SetField(order.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := oc.mutation.Profit(); ok {
		_spec.SetField(order.FieldProfit, field.TypeString, value)
		_node.Profit = &value
	}
	return _node, _spec
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
}

// Save creates the Order entities in the database.
func (ocb *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Order, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
