// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/sol-grid-bot/internal/ent/settings"
)

// Settings is the model entity for the Settings schema.
type Settings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId int64 `json:"userId,omitempty"`
	// MaxRetries holds the value of the "maxRetries" field.
	MaxRetries int64 `json:"maxRetries,omitempty"`
	// SlippageBps holds the value of the "slippageBps" field.
	SlippageBps int `json:"slippageBps,omitempty"`
	// SellSlippageBps holds the value of the "sellSlippageBps" field.
	SellSlippageBps *int `json:"sellSlippageBps,omitempty"`
	// ExitSlippageBps holds the value of the "exitSlippageBps" field.
	ExitSlippageBps *int `json:"exitSlippageBps,omitempty"`
	// MaxLamports holds the value of the "maxLamports" field.
	MaxLamports int64 `json:"maxLamports,omitempty"`
	// PriorityLevel holds the value of the "priorityLevel" field.
	PriorityLevel settings.PriorityLevel `json:"priorityLevel,omitempty"`
	// DexAggregator holds the value of the "dexAggregator" field.
	DexAggregator settings.DexAggregator `json:"dexAggregator,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Settings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case settings.FieldID, settings.FieldUserId, settings.FieldMaxRetries, settings.FieldSlippageBps, settings.FieldSellSlippageBps, settings.FieldExitSlippageBps, settings.FieldMaxLamports:
			values[i] = new(sql.NullInt64)
		case settings.FieldPriorityLevel, settings.FieldDexAggregator:
			values[i] = new(sql.NullString)
		case settings.FieldCreateTime, settings.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Settings fields.
func (s *Settings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case settings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case settings.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				s.CreateTime = value.Time
			}
		case settings.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				s.UpdateTime = value.Time
			}
		case settings.FieldUserId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				s.UserId = value.Int64
			}
		case settings.FieldMaxRetries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field maxRetries", values[i])
			} else if value.Valid {
				s.MaxRetries = value.Int64
			}
		case settings.FieldSlippageBps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field slippageBps", values[i])
			} else if value.Valid {
				s.SlippageBps = int(value.Int64)
			}
		case settings.FieldSellSlippageBps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sellSlippageBps", values[i])
			} else if value.Valid {
				s.SellSlippageBps = new(int)
				*s.SellSlippageBps = int(value.Int64)
			}
		case settings.FieldExitSlippageBps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exitSlippageBps", values[i])
			} else if value.Valid {
				s.ExitSlippageBps = new(int)
				*s.ExitSlippageBps = int(value.Int64)
			}
		case settings.FieldMaxLamports:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field maxLamports", values[i])
			} else if value.Valid {
				s.MaxLamports = value.Int64
			}
		case settings.FieldPriorityLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priorityLevel", values[i])
			} else if value.Valid {
				s.PriorityLevel = settings.PriorityLevel(value.String)
			}
		case settings.FieldDexAggregator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dexAggregator", values[i])
			} else if value.Valid {
				s.DexAggregator = settings.DexAggregator(value.String)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Settings.
// This includes values selected through modifiers, order, etc.
func (s *Settings) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// Update returns a builder for updating this Settings.
// Note that you need to call Settings.Unwrap() before calling this method if this Settings
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Settings) Update() *SettingsUpdateOne {
	return NewSettingsClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Settings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Settings) Unwrap() *Settings {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Settings is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Settings) String() string {
	var builder strings.Builder
	builder.WriteString("Settings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("create_time=")
	builder.WriteString(s.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(s.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("userId=")
	builder.WriteString(fmt.Sprintf("%v", s.UserId))
	builder.WriteString(", ")
	builder.WriteString("maxRetries=")
	builder.WriteString(fmt.Sprintf("%v", s.MaxRetries))
	builder.WriteString(", ")
	builder.WriteString("slippageBps=")
	builder.WriteString(fmt.Sprintf("%v", s.SlippageBps))
	builder.WriteString(", ")
	if v := s.SellSlippageBps; v != nil {
		builder.WriteString("sellSlippageBps=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := s.ExitSlippageBps; v != nil {
		builder.WriteString("exitSlippageBps=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("maxLamports=")
	builder.WriteString(fmt.Sprintf("%v", s.MaxLamports))
	builder.WriteString(", ")
	builder.WriteString("priorityLevel=")
	builder.WriteString(fmt.Sprintf("%v", s.PriorityLevel))
	builder.WriteString(", ")
	builder.WriteString("dexAggregator=")
	builder.WriteString(fmt.Sprintf("%v", s.DexAggregator))
	builder.WriteByte(')')
	return builder.String()
}

// SettingsSlice is a parsable slice of Settings.
type SettingsSlice []*Settings
