// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/predicate"
	"github.com/fachebot/sol-grid-bot/internal/ent/settings"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdateTime sets the "update_time" field.
func (su *SettingsUpdate) SetUpdateTime(t time.Time) *SettingsUpdate {
	su.mutation.SetUpdateTime(t)
	return su
}

// SetUserId sets the "userId" field.
func (su *SettingsUpdate) SetUserId(i int64) *SettingsUpdate {
	su.mutation.ResetUserId()
	su.mutation.SetUserId(i)
	return su
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableUserId(i *int64) *SettingsUpdate {
	if i != nil {
		su.SetUserId(*i)
	}
	return su
}

// AddUserId adds i to the "userId" field.
func (su *SettingsUpdate) AddUserId(i int64) *SettingsUpdate {
	su.mutation.AddUserId(i)
	return su
}

// SetMaxRetries sets the "maxRetries" field.
func (su *SettingsUpdate) SetMaxRetries(i int64) *SettingsUpdate {
	su.mutation.ResetMaxRetries()
	su.mutation.SetMaxRetries(i)
	return su
}

// SetNillableMaxRetries sets the "maxRetries" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableMaxRetries(i *int64) *SettingsUpdate {
	if i != nil {
		su.SetMaxRetries(*i)
	}
	return su
}

// AddMaxRetries adds i to the "maxRetries" field.
func (su *SettingsUpdate) AddMaxRetries(i int64) *SettingsUpdate {
	su.mutation.AddMaxRetries(i)
	return su
}

// SetSlippageBps sets the "slippageBps" field.
func (su *SettingsUpdate) SetSlippageBps(i int) *SettingsUpdate {
	su.mutation.ResetSlippageBps()
	su.mutation.SetSlippageBps(i)
	return su
}

// SetNillableSlippageBps sets the "slippageBps" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableSlippageBps(i *int) *SettingsUpdate {
	if i != nil {
		su.SetSlippageBps(*i)
	}
	return su
}

// AddSlippageBps adds i to the "slippageBps" field.
func (su *SettingsUpdate) AddSlippageBps(i int) *SettingsUpdate {
	su.mutation.AddSlippageBps(i)
	return su
}

// SetSellSlippageBps sets the "sellSlippageBps" field.
func (su *SettingsUpdate) SetSellSlippageBps(i int) *SettingsUpdate {
	su.mutation.ResetSellSlippageBps()
	su.mutation.SetSellSlippageBps(i)
	return su
}

// SetNillableSellSlippageBps sets the "sellSlippageBps" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableSellSlippageBps(i *int) *SettingsUpdate {
	if i != nil {
		su.SetSellSlippageBps(*i)
	}
	return su
}

// AddSellSlippageBps adds i to the "sellSlippageBps" field.
func (su *SettingsUpdate) AddSellSlippageBps(i int) *SettingsUpdate {
	su.mutation.AddSellSlippageBps(i)
	return su
}

// ClearSellSlippageBps clears the value of the "sellSlippageBps" field.
func (su *SettingsUpdate) ClearSellSlippageBps() *SettingsUpdate {
	su.mutation.ClearSellSlippageBps()
	return su
}

// SetExitSlippageBps sets the "exitSlippageBps" field.
func (su *SettingsUpdate) SetExitSlippageBps(i int) *SettingsUpdate {
	su.mutation.ResetExitSlippageBps()
	su.mutation.SetExitSlippageBps(i)
	return su
}

// SetNillableExitSlippageBps sets the "exitSlippageBps" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableExitSlippageBps(i *int) *SettingsUpdate {
	if i != nil {
		su.SetExitSlippageBps(*i)
	}
	return su
}

// AddExitSlippageBps adds i to the "exitSlippageBps" field.
func (su *SettingsUpdate) AddExitSlippageBps(i int) *SettingsUpdate {
	su.mutation.AddExitSlippageBps(i)
	return su
}

// ClearExitSlippageBps clears the value of the "exitSlippageBps" field.
func (su *SettingsUpdate) ClearExitSlippageBps() *SettingsUpdate {
	su.mutation.ClearExitSlippageBps()
	return su
}

// SetMaxLamports sets the "maxLamports" field.
func (su *SettingsUpdate) SetMaxLamports(i int64) *SettingsUpdate {
	su.mutation.ResetMaxLamports()
	su.mutation.SetMaxLamports(i)
	return su
}

// SetNillableMaxLamports sets the "maxLamports" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableMaxLamports(i *int64) *SettingsUpdate {
	if i != nil {
		su.SetMaxLamports(*i)
	}
	return su
}

// AddMaxLamports adds i to the "maxLamports" field.
func (su *SettingsUpdate) AddMaxLamports(i int64) *SettingsUpdate {
	su.mutation.AddMaxLamports(i)
	return su
}

// SetPriorityLevel sets the "priorityLevel" field.
func (su *SettingsUpdate) SetPriorityLevel(sl settings.PriorityLevel) *SettingsUpdate {
	su.mutation.SetPriorityLevel(sl)
	return su
}

// SetNillablePriorityLevel sets the "priorityLevel" field if the given value is not nil.
func (su *SettingsUpdate) SetNillablePriorityLevel(sl *settings.PriorityLevel) *SettingsUpdate {
	if sl != nil {
		su.SetPriorityLevel(*sl)
	}
	return su
}

// SetDexAggregator sets the "dexAggregator" field.
func (su *SettingsUpdate) SetDexAggregator(sa settings.DexAggregator) *SettingsUpdate {
	su.mutation.SetDexAggregator(sa)
	return su
}

// SetNillableDexAggregator sets the "dexAggregator" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableDexAggregator(sa *settings.DexAggregator) *SettingsUpdate {
	if sa != nil {
		su.SetDexAggregator(*sa)
	}
	return su
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SettingsUpdate) defaults() {
	if _, ok := su.mutation.UpdateTime(); !ok {
		v := settings.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SettingsUpdate) check() error {
	if v, ok := su.mutation.MaxRetries(); ok {
		if err := settings.MaxRetriesValidator(v); err != nil {
			return &ValidationError{Name: "maxRetries", err: fmt.Errorf(`ent: validator failed for field "Settings.maxRetries": %w`, err)}
		}
	}
	if v, ok := su.mutation.SlippageBps(); ok {
		if err := settings.SlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "slippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.slippageBps": %w`, err)}
		}
	}
	if v, ok := su.mutation.SellSlippageBps(); ok {
		if err := settings.SellSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "sellSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.sellSlippageBps": %w`, err)}
		}
	}
	if v, ok := su.mutation.ExitSlippageBps(); ok {
		if err := settings.ExitSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "exitSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.exitSlippageBps": %w`, err)}
		}
	}
	if v, ok := su.mutation.MaxLamports(); ok {
		if err := settings.MaxLamportsValidator(v); err != nil {
			return &ValidationError{Name: "maxLamports", err: fmt.Errorf(`ent: validator failed for field "Settings.maxLamports": %w`, err)}
		}
	}
	if v, ok := su.mutation.PriorityLevel(); ok {
		if err := settings.PriorityLevelValidator(v); err != nil {
			return &ValidationError{Name: "priorityLevel", err: fmt.Errorf(`ent: validator failed for field "Settings.priorityLevel": %w`, err)}
		}
	}
	if v, ok := su.mutation.DexAggregator(); ok {
		if err := settings.DexAggregatorValidator(v); err != nil {
			return &ValidationError{Name: "dexAggregator", err: fmt.Errorf(`ent: validator failed for field "Settings.dexAggregator": %w`, err)}
		}
	}
	return nil
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.SetField(settings.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.UserId(); ok {
		_spec.SetField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedUserId(); ok {
		_spec.AddField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := su.mutation.MaxRetries(); ok {
		_spec.SetField(settings.FieldMaxRetries, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedMaxRetries(); ok {
		_spec.AddField(settings.FieldMaxRetries, field.TypeInt64, value)
	}
	if value, ok := su.mutation.SlippageBps(); ok {
		_spec.SetField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedSlippageBps(); ok {
		_spec.AddField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := su.mutation.SellSlippageBps(); ok {
		_spec.SetField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedSellSlippageBps(); ok {
		_spec.AddField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if su.mutation.SellSlippageBpsCleared() {
		_spec.ClearField(settings.FieldSellSlippageBps, field.TypeInt)
	}
	if value, ok := su.mutation.ExitSlippageBps(); ok {
		_spec.SetField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedExitSlippageBps(); ok {
		_spec.AddField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if su.mutation.ExitSlippageBpsCleared() {
		_spec.ClearField(settings.FieldExitSlippageBps, field.TypeInt)
	}
	if value, ok := su.mutation.MaxLamports(); ok {
		_spec.SetField(settings.FieldMaxLamports, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedMaxLamports(); ok {
		_spec.AddField(settings.FieldMaxLamports, field.TypeInt64, value)
	}
	if value, ok := su.mutation.PriorityLevel(); ok {
		_spec.SetField(settings.FieldPriorityLevel, field.TypeEnum, value)
	}
	if value, ok := su.mutation.DexAggregator(); ok {
		_spec.SetField(settings.FieldDexAggregator, field.TypeEnum, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetUpdateTime sets the "update_time" field.
func (suo *SettingsUpdateOne) SetUpdateTime(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetUpdateTime(t)
	return suo
}

// SetUserId sets the "userId" field.
func (suo *SettingsUpdateOne) SetUserId(i int64) *SettingsUpdateOne {
	suo.mutation.ResetUserId()
	suo.mutation.SetUserId(i)
	return suo
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableUserId(i *int64) *SettingsUpdateOne {
	if i != nil {
		suo.SetUserId(*i)
	}
	return suo
}

// AddUserId adds i to the "userId" field.
func (suo *SettingsUpdateOne) AddUserId(i int64) *SettingsUpdateOne {
	suo.mutation.AddUserId(i)
	return suo
}

// SetMaxRetries sets the "maxRetries" field.
func (suo *SettingsUpdateOne) SetMaxRetries(i int64) *SettingsUpdateOne {
	suo.mutation.ResetMaxRetries()
	suo.mutation.SetMaxRetries(i)
	return suo
}

// SetNillableMaxRetries sets the "maxRetries" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableMaxRetries(i *int64) *SettingsUpdateOne {
	if i != nil {
		suo.SetMaxRetries(*i)
	}
	return suo
}

// AddMaxRetries adds i to the "maxRetries" field.
func (suo *SettingsUpdateOne) AddMaxRetries(i int64) *SettingsUpdateOne {
	suo.mutation.AddMaxRetries(i)
	return suo
}

// SetSlippageBps sets the "slippageBps" field.
func (suo *SettingsUpdateOne) SetSlippageBps(i int) *SettingsUpdateOne {
	suo.mutation.ResetSlippageBps()
	suo.mutation.SetSlippageBps(i)
	return suo
}

// SetNillableSlippageBps sets the "slippageBps" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableSlippageBps(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetSlippageBps(*i)
	}
	return suo
}

// AddSlippageBps adds i to the "slippageBps" field.
func (suo *SettingsUpdateOne) AddSlippageBps(i int) *SettingsUpdateOne {
	suo.mutation.AddSlippageBps(i)
	return suo
}

// SetSellSlippageBps sets the "sellSlippageBps" field.
func (suo *SettingsUpdateOne) SetSellSlippageBps(i int) *SettingsUpdateOne {
	suo.mutation.ResetSellSlippageBps()
	suo.mutation.SetSellSlippageBps(i)
	return suo
}

// SetNillableSellSlippageBps sets the "sellSlippageBps" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableSellSlippageBps(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetSellSlippageBps(*i)
	}
	return suo
}

// AddSellSlippageBps adds i to the "sellSlippageBps" field.
func (suo *SettingsUpdateOne) AddSellSlippageBps(i int) *SettingsUpdateOne {
	suo.mutation.AddSellSlippageBps(i)
	return suo
}

// ClearSellSlippageBps clears the value of the "sellSlippageBps" field.
func (suo *SettingsUpdateOne) ClearSellSlippageBps() *SettingsUpdateOne {
	suo.mutation.ClearSellSlippageBps()
	return suo
}

// SetExitSlippageBps sets the "exitSlippageBps" field.
func (suo *SettingsUpdateOne) SetExitSlippageBps(i int) *SettingsUpdateOne {
	suo.mutation.ResetExitSlippageBps()
	suo.mutation.SetExitSlippageBps(i)
	return suo
}

// SetNillableExitSlippageBps sets the "exitSlippageBps" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableExitSlippageBps(i *int) *SettingsUpdateOne {
	if i != nil {
		suo.SetExitSlippageBps(*i)
	}
	return suo
}

// AddExitSlippageBps adds i to the "exitSlippageBps" field.
func (suo *SettingsUpdateOne) AddExitSlippageBps(i int) *SettingsUpdateOne {
	suo.mutation.AddExitSlippageBps(i)
	return suo
}

// ClearExitSlippageBps clears the value of the "exitSlippageBps" field.
func (suo *SettingsUpdateOne) ClearExitSlippageBps() *SettingsUpdateOne {
	suo.mutation.ClearExitSlippageBps()
	return suo
}

// SetMaxLamports sets the "maxLamports" field.
func (suo *SettingsUpdateOne) SetMaxLamports(i int64) *SettingsUpdateOne {
	suo.mutation.ResetMaxLamports()
	suo.mutation.SetMaxLamports(i)
	return suo
}

// SetNillableMaxLamports sets the "maxLamports" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableMaxLamports(i *int64) *SettingsUpdateOne {
	if i != nil {
		suo.SetMaxLamports(*i)
	}
	return suo
}

// AddMaxLamports adds i to the "maxLamports" field.
func (suo *SettingsUpdateOne) AddMaxLamports(i int64) *SettingsUpdateOne {
	suo.mutation.AddMaxLamports(i)
	return suo
}

// SetPriorityLevel sets the "priorityLevel" field.
func (suo *SettingsUpdateOne) SetPriorityLevel(sl settings.PriorityLevel) *SettingsUpdateOne {
	suo.mutation.SetPriorityLevel(sl)
	return suo
}

// SetNillablePriorityLevel sets the "priorityLevel" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillablePriorityLevel(sl *settings.PriorityLevel) *SettingsUpdateOne {
	if sl != nil {
		suo.SetPriorityLevel(*sl)
	}
	return suo
}

// SetDexAggregator sets the "dexAggregator" field.
func (suo *SettingsUpdateOne) SetDexAggregator(sa settings.DexAggregator) *SettingsUpdateOne {
	suo.mutation.SetDexAggregator(sa)
	return suo
}

// SetNillableDexAggregator sets the "dexAggregator" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableDexAggregator(sa *settings.DexAggregator) *SettingsUpdateOne {
	if sa != nil {
		suo.SetDexAggregator(*sa)
	}
	return suo
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SettingsUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		v := settings.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SettingsUpdateOne) check() error {
	if v, ok := suo.mutation.MaxRetries(); ok {
		if err := settings.MaxRetriesValidator(v); err != nil {
			return &ValidationError{Name: "maxRetries", err: fmt.Errorf(`ent: validator failed for field "Settings.maxRetries": %w`, err)}
		}
	}
	if v, ok := suo.mutation.SlippageBps(); ok {
		if err := settings.SlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "slippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.slippageBps": %w`, err)}
		}
	}
	if v, ok := suo.mutation.SellSlippageBps(); ok {
		if err := settings.SellSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "sellSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.sellSlippageBps": %w`, err)}
		}
	}
	if v, ok := suo.mutation.ExitSlippageBps(); ok {
		if err := settings.ExitSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "exitSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.exitSlippageBps": %w`, err)}
		}
	}
	if v, ok := suo.mutation.MaxLamports(); ok {
		if err := settings.MaxLamportsValidator(v); err != nil {
			return &ValidationError{Name: "maxLamports", err: fmt.Errorf(`ent: validator failed for field "Settings.maxLamports": %w`, err)}
		}
	}
	if v, ok := suo.mutation.PriorityLevel(); ok {
		if err := settings.PriorityLevelValidator(v); err != nil {
			return &ValidationError{Name: "priorityLevel", err: fmt.Errorf(`ent: validator failed for field "Settings.priorityLevel": %w`, err)}
		}
	}
	if v, ok := suo.mutation.DexAggregator(); ok {
		if err := settings.DexAggregatorValidator(v); err != nil {
			return &ValidationError{Name: "dexAggregator", err: fmt.Errorf(`ent: validator failed for field "Settings.dexAggregator": %w`, err)}
		}
	}
	return nil
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.SetField(settings.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.UserId(); ok {
		_spec.SetField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedUserId(); ok {
		_spec.AddField(settings.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.MaxRetries(); ok {
		_spec.SetField(settings.FieldMaxRetries, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedMaxRetries(); ok {
		_spec.AddField(settings.FieldMaxRetries, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.SlippageBps(); ok {
		_spec.SetField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedSlippageBps(); ok {
		_spec.AddField(settings.FieldSlippageBps, field.TypeInt, value)
	}
	if value, ok := suo.mutation.SellSlippageBps(); ok {
		_spec.SetField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedSellSlippageBps(); ok {
		_spec.AddField(settings.FieldSellSlippageBps, field.TypeInt, value)
	}
	if suo.mutation.SellSlippageBpsCleared() {
		_spec.ClearField(settings.FieldSellSlippageBps, field.TypeInt)
	}
	if value, ok := suo.mutation.ExitSlippageBps(); ok {
		_spec.SetField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedExitSlippageBps(); ok {
		_spec.AddField(settings.FieldExitSlippageBps, field.TypeInt, value)
	}
	if suo.mutation.ExitSlippageBpsCleared() {
		_spec.ClearField(settings.FieldExitSlippageBps, field.TypeInt)
	}
	if value, ok := suo.mutation.MaxLamports(); ok {
		_spec.SetField(settings.FieldMaxLamports, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedMaxLamports(); ok {
		_spec.AddField(settings.FieldMaxLamports, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.PriorityLevel(); ok {
		_spec.SetField(settings.FieldPriorityLevel, field.TypeEnum, value)
	}
	if value, ok := suo.mutation.DexAggregator(); ok {
		_spec.SetField(settings.FieldDexAggregator, field.TypeEnum, value)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
