// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/settings"
)

// SettingsCreate is the builder for creating a Settings entity.
type SettingsCreate struct {
	config
	mutation *SettingsMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (sc *SettingsCreate) SetCreateTime(t time.Time) *SettingsCreate {
	sc.mutation.SetCreateTime(t)
	return sc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sc *SettingsCreate) SetNillableCreateTime(t *time.Time) *SettingsCreate {
	if t != nil {
		sc.SetCreateTime(*t)
	}
	return sc
}

// SetUpdateTime sets the "update_time" field.
func (sc *SettingsCreate) SetUpdateTime(t time.Time) *SettingsCreate {
	sc.mutation.SetUpdateTime(t)
	return sc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sc *SettingsCreate) SetNillableUpdateTime(t *time.Time) *SettingsCreate {
	if t != nil {
		sc.SetUpdateTime(*t)
	}
	return sc
}

// SetUserId sets the "userId" field.
func (sc *SettingsCreate) SetUserId(i int64) *SettingsCreate {
	sc.mutation.SetUserId(i)
	return sc
}

// SetMaxRetries sets the "maxRetries" field.
func (sc *SettingsCreate) SetMaxRetries(i int64) *SettingsCreate {
	sc.mutation.SetMaxRetries(i)
	return sc
}

// SetSlippageBps sets the "slippageBps" field.
func (sc *SettingsCreate) SetSlippageBps(i int) *SettingsCreate {
	sc.mutation.SetSlippageBps(i)
	return sc
}

// SetSellSlippageBps sets the "sellSlippageBps" field.
func (sc *SettingsCreate) SetSellSlippageBps(i int) *SettingsCreate {
	sc.mutation.SetSellSlippageBps(i)
	return sc
}

// SetNillableSellSlippageBps sets the "sellSlippageBps" field if the given value is not nil.
func (sc *SettingsCreate) SetNillableSellSlippageBps(i *int) *SettingsCreate {
	if i != nil {
		sc.SetSellSlippageBps(*i)
	}
	return sc
}

// SetExitSlippageBps sets the "exitSlippageBps" field.
func (sc *SettingsCreate) SetExitSlippageBps(i int) *SettingsCreate {
	sc.mutation.SetExitSlippageBps(i)
	return sc
}

// SetNillableExitSlippageBps sets the "exitSlippageBps" field if the given value is not nil.
func (sc *SettingsCreate) SetNillableExitSlippageBps(i *int) *SettingsCreate {
	if i != nil {
		sc.SetExitSlippageBps(*i)
	}
	return sc
}

// SetMaxLamports sets the "maxLamports" field.
func (sc *SettingsCreate) SetMaxLamports(i int64) *SettingsCreate {
	sc.mutation.SetMaxLamports(i)
	return sc
}

// SetPriorityLevel sets the "priorityLevel" field.
func (sc *SettingsCreate) SetPriorityLevel(sl settings.PriorityLevel) *SettingsCreate {
	sc.mutation.SetPriorityLevel(sl)
	return sc
}

// SetDexAggregator sets the "dexAggregator" field.
func (sc *SettingsCreate) SetDexAggregator(sa settings.DexAggregator) *SettingsCreate {
	sc.mutation.SetDexAggregator(sa)
	return sc
}

// Mutation returns the SettingsMutation object of the builder.
func (sc *SettingsCreate) Mutation() *SettingsMutation {
	return sc.mutation
}

// Save creates the Settings in the database.
func (sc *SettingsCreate) Save(ctx context.Context) (*Settings, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SettingsCreate) SaveX(ctx context.Context) *Settings {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SettingsCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SettingsCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SettingsCreate) defaults() {
	if _, ok := sc.mutation.CreateTime(); !ok {
		v := settings.DefaultCreateTime()
		sc.mutation.SetCreateTime(v)
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		v := settings.DefaultUpdateTime()
		sc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SettingsCreate) check() error {
	if _, ok := sc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Settings.create_time"`)}
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Settings.update_time"`)}
	}
	if _, ok := sc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "Settings.userId"`)}
	}
	if _, ok := sc.mutation.MaxRetries(); !ok {
		return &ValidationError{Name: "maxRetries", err: errors.New(`ent: missing required field "Settings.maxRetries"`)}
	}
	if v, ok := sc.mutation.MaxRetries(); ok {
		if err := settings.MaxRetriesValidator(v); err != nil {
			return &ValidationError{Name: "maxRetries", err: fmt.Errorf(`ent: validator failed for field "Settings.maxRetries": %w`, err)}
		}
	}
	if _, ok := sc.mutation.SlippageBps(); !ok {
		return &ValidationError{Name: "slippageBps", err: errors.New(`ent: missing required field "Settings.slippageBps"`)}
	}
	if v, ok := sc.mutation.SlippageBps(); ok {
		if err := settings.SlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "slippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.slippageBps": %w`, err)}
		}
	}
	if v, ok := sc.mutation.SellSlippageBps(); ok {
		if err := settings.SellSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "sellSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.sellSlippageBps": %w`, err)}
		}
	}
	if v, ok := sc.mutation.ExitSlippageBps(); ok {
		if err := settings.ExitSlippageBpsValidator(v); err != nil {
			return &ValidationError{Name: "exitSlippageBps", err: fmt.Errorf(`ent: validator failed for field "Settings.exitSlippageBps": %w`, err)}
		}
	}
	if _, ok := sc.mutation.MaxLamports(); !ok {
		return &ValidationError{Name: "maxLamports", err: errors.New(`ent: missing required field "Settings.maxLamports"`)}
	}
	if v, ok := sc.mutation.MaxLamports(); ok {
		if err := settings.MaxLamportsValidator(v); err != nil {
			return &ValidationError{Name: "maxLamports", err: fmt.Errorf(`ent: validator failed for field "Settings.maxLamports": %w`, err)}
		}
	}
	if _, ok := sc.mutation.PriorityLevel(); !ok {
		return &ValidationError{Name: "priorityLevel", err: errors.New(`ent: missing required field "Settings.priorityLevel"`)}
	}
	if v, ok := sc.mutation.PriorityLevel(); ok {
		if err := settings.PriorityLevelValidator(v); err != nil {
			return &ValidationError{Name: "priorityLevel", err: fmt.Errorf(`ent: validator failed for field "Settings.priorityLevel": %w`, err)}
		}
	}
	if _, ok := sc.mutation.DexAggregator(); !ok {
		return &ValidationError{Name: "dexAggregator", err: errors.New(`ent: missing required field "Settings.dexAggregator"`)}
	}
	if v, ok := sc.mutation.DexAggregator(); ok {
		if err := settings.DexAggregatorValidator(v); err != nil {
			return &ValidationError{Name: "dexAggregator", err: fmt.Errorf(`ent: validator failed for field "Settings.dexAggregator": %w`, err)}
		}
	}
	return nil
}

func (sc *SettingsCreate) sqlSave(ctx context.Context) (*Settings, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SettingsCreate) createSpec() (*Settings, *sqlgraph.CreateSpec) {
	var (
		_node = &Settings{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(settings.Table, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.CreateTime(); ok {
		_spec.SetField(settings.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := sc.mutation.UpdateTime(); ok {
		_spec.SetField(settings.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := sc.mutation.UserId(); ok {
		_spec.SetField(settings.FieldUserId, field.TypeInt64, value)
		_node.UserId = value
	}
	if value, ok := sc.mutation.MaxRetries(); ok {
		_spec.SetField(settings.FieldMaxRetries, field.TypeInt64, value)
		_node.MaxRetries = value
	}
	if value, ok := sc.mutation.SlippageBps(); ok {
		_spec.SetField(settings.FieldSlippageBps, field.TypeInt, value)
		_node.SlippageBps = value
	}
	if value, ok := sc.mutation.SellSlippageBps(); ok {
		_spec.SetField(settings.FieldSellSlippageBps, field.TypeInt, value)
		_node.SellSlippageBps = &value
	}
	if value, ok := sc.mutation.ExitSlippageBps(); ok {
		_spec.SetField(settings.FieldExitSlippageBps, field.TypeInt, value)
		_node.ExitSlippageBps = &value
	}
	if value, ok := sc.mutation.MaxLamports(); ok {
		_spec.SetField(settings.FieldMaxLamports, field.TypeInt64, value)
		_node.MaxLamports = value
	}
	if value, ok := sc.mutation.PriorityLevel(); ok {
		_spec.SetField(settings.FieldPriorityLevel, field.TypeEnum, value)
		_node.PriorityLevel = value
	}
	if value, ok := sc.mutation.DexAggregator(); ok {
		_spec.SetField(settings.FieldDexAggregator, field.TypeEnum, value)
		_node.DexAggregator = value
	}
	return _node, _spec
}

// SettingsCreateBulk is the builder for creating many Settings entities in bulk.
type SettingsCreateBulk struct {
	config
	err      error
	builders []*SettingsCreate
}

// Save creates the Settings entities in the database.
func (scb *SettingsCreateBulk) Save(ctx context.Context) ([]*Settings, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Settings, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SettingsCreateBulk) SaveX(ctx context.Context) []*Settings {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SettingsCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
