// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/predicate"
	"github.com/fachebot/sol-grid-bot/internal/ent/strategy"
	"github.com/shopspring/decimal"
)

// StrategyUpdate is the builder for updating Strategy entities.
type StrategyUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyMutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (su *StrategyUpdate) Where(ps ...predicate.Strategy) *StrategyUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdateTime sets the "update_time" field.
func (su *StrategyUpdate) SetUpdateTime(t time.Time) *StrategyUpdate {
	su.mutation.SetUpdateTime(t)
	return su
}

// SetGUID sets the "guid" field.
func (su *StrategyUpdate) SetGUID(s string) *StrategyUpdate {
	su.mutation.SetGUID(s)
	return su
}

// SetNillableGUID sets the "guid" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableGUID(s *string) *StrategyUpdate {
	if s != nil {
		su.SetGUID(*s)
	}
	return su
}

// SetUserId sets the "userId" field.
func (su *StrategyUpdate) SetUserId(i int64) *StrategyUpdate {
	su.mutation.ResetUserId()
	su.mutation.SetUserId(i)
	return su
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableUserId(i *int64) *StrategyUpdate {
	if i != nil {
		su.SetUserId(*i)
	}
	return su
}

// AddUserId adds i to the "userId" field.
func (su *StrategyUpdate) AddUserId(i int64) *StrategyUpdate {
	su.mutation.AddUserId(i)
	return su
}

// SetToken sets the "token" field.
func (su *StrategyUpdate) SetToken(s string) *StrategyUpdate {
	su.mutation.SetToken(s)
	return su
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableToken(s *string) *StrategyUpdate {
	if s != nil {
		su.SetToken(*s)
	}
	return su
}

// SetSymbol sets the "symbol" field.
func (su *StrategyUpdate) SetSymbol(s string) *StrategyUpdate {
	su.mutation.SetSymbol(s)
	return su
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableSymbol(s *string) *StrategyUpdate {
	if s != nil {
		su.SetSymbol(*s)
	}
	return su
}

// SetMartinFactor sets the "martinFactor" field.
func (su *StrategyUpdate) SetMartinFactor(f float64) *StrategyUpdate {
	su.mutation.ResetMartinFactor()
	su.mutation.SetMartinFactor(f)
	return su
}

// SetNillableMartinFactor sets the "martinFactor" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableMartinFactor(f *float64) *StrategyUpdate {
	if f != nil {
		su.SetMartinFactor(*f)
	}
	return su
}

// AddMartinFactor adds f to the "martinFactor" field.
func (su *StrategyUpdate) AddMartinFactor(f float64) *StrategyUpdate {
	su.mutation.AddMartinFactor(f)
	return su
}

// SetMaxGridLimit sets the "maxGridLimit" field.
func (su *StrategyUpdate) SetMaxGridLimit(i int) *StrategyUpdate {
	su.mutation.ResetMaxGridLimit()
	su.mutation.SetMaxGridLimit(i)
	return su
}

// SetNillableMaxGridLimit sets the "maxGridLimit" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableMaxGridLimit(i *int) *StrategyUpdate {
	if i != nil {
		su.SetMaxGridLimit(*i)
	}
	return su
}

// AddMaxGridLimit adds i to the "maxGridLimit" field.
func (su *StrategyUpdate) AddMaxGridLimit(i int) *StrategyUpdate {
	su.mutation.AddMaxGridLimit(i)
	return su
}

// ClearMaxGridLimit clears the value of the "maxGridLimit" field.
func (su *StrategyUpdate) ClearMaxGridLimit() *StrategyUpdate {
	su.mutation.ClearMaxGridLimit()
	return su
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (su *StrategyUpdate) SetTakeProfitRatio(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetTakeProfitRatio(d)
	return su
}

// SetNillableTakeProfitRatio sets the "takeProfitRatio" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableTakeProfitRatio(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetTakeProfitRatio(*d)
	}
	return su
}

// SetUpperPriceBound sets the "upperPriceBound" field.
func (su *StrategyUpdate) SetUpperPriceBound(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetUpperPriceBound(d)
	return su
}

// SetNillableUpperPriceBound sets the "upperPriceBound" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableUpperPriceBound(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetUpperPriceBound(*d)
	}
	return su
}

// SetLowerPriceBound sets the "lowerPriceBound" field.
func (su *StrategyUpdate) SetLowerPriceBound(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetLowerPriceBound(d)
	return su
}

// SetNillableLowerPriceBound sets the "lowerPriceBound" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableLowerPriceBound(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetLowerPriceBound(*d)
	}
	return su
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (su *StrategyUpdate) SetInitialOrderSize(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetInitialOrderSize(d)
	return su
}

// SetNillableInitialOrderSize sets the "initialOrderSize" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableInitialOrderSize(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetInitialOrderSize(*d)
	}
	return su
}

// SetLastKlineVolume sets the "lastKlineVolume" field.
func (su *StrategyUpdate) SetLastKlineVolume(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetLastKlineVolume(d)
	return su
}

// SetNillableLastKlineVolume sets the "lastKlineVolume" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableLastKlineVolume(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetLastKlineVolume(*d)
	}
	return su
}

// ClearLastKlineVolume clears the value of the "lastKlineVolume" field.
func (su *StrategyUpdate) ClearLastKlineVolume() *StrategyUpdate {
	su.mutation.ClearLastKlineVolume()
	return su
}

// SetFiveKlineVolume sets the "fiveKlineVolume" field.
func (su *StrategyUpdate) SetFiveKlineVolume(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetFiveKlineVolume(d)
	return su
}

// SetNillableFiveKlineVolume sets the "fiveKlineVolume" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableFiveKlineVolume(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetFiveKlineVolume(*d)
	}
	return su
}

// ClearFiveKlineVolume clears the value of the "fiveKlineVolume" field.
func (su *StrategyUpdate) ClearFiveKlineVolume() *StrategyUpdate {
	su.mutation.ClearFiveKlineVolume()
	return su
}

// SetFirstOrderId sets the "firstOrderId" field.
func (su *StrategyUpdate) SetFirstOrderId(i int) *StrategyUpdate {
	su.mutation.ResetFirstOrderId()
	su.mutation.SetFirstOrderId(i)
	return su
}

// SetNillableFirstOrderId sets the "firstOrderId" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableFirstOrderId(i *int) *StrategyUpdate {
	if i != nil {
		su.SetFirstOrderId(*i)
	}
	return su
}

// AddFirstOrderId adds i to the "firstOrderId" field.
func (su *StrategyUpdate) AddFirstOrderId(i int) *StrategyUpdate {
	su.mutation.AddFirstOrderId(i)
	return su
}

// ClearFirstOrderId clears the value of the "firstOrderId" field.
func (su *StrategyUpdate) ClearFirstOrderId() *StrategyUpdate {
	su.mutation.ClearFirstOrderId()
	return su
}

// SetUpperBoundExit sets the "upperBoundExit" field.
func (su *StrategyUpdate) SetUpperBoundExit(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetUpperBoundExit(d)
	return su
}

// SetNillableUpperBoundExit sets the "upperBoundExit" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableUpperBoundExit(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetUpperBoundExit(*d)
	}
	return su
}

// ClearUpperBoundExit clears the value of the "upperBoundExit" field.
func (su *StrategyUpdate) ClearUpperBoundExit() *StrategyUpdate {
	su.mutation.ClearUpperBoundExit()
	return su
}

// SetStopLossExit sets the "stopLossExit" field.
func (su *StrategyUpdate) SetStopLossExit(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetStopLossExit(d)
	return su
}

// SetNillableStopLossExit sets the "stopLossExit" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableStopLossExit(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetStopLossExit(*d)
	}
	return su
}

// ClearStopLossExit clears the value of the "stopLossExit" field.
func (su *StrategyUpdate) ClearStopLossExit() *StrategyUpdate {
	su.mutation.ClearStopLossExit()
	return su
}

// SetTakeProfitExit sets the "takeProfitExit" field.
func (su *StrategyUpdate) SetTakeProfitExit(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetTakeProfitExit(d)
	return su
}

// SetNillableTakeProfitExit sets the "takeProfitExit" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableTakeProfitExit(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetTakeProfitExit(*d)
	}
	return su
}

// ClearTakeProfitExit clears the value of the "takeProfitExit" field.
func (su *StrategyUpdate) ClearTakeProfitExit() *StrategyUpdate {
	su.mutation.ClearTakeProfitExit()
	return su
}

// SetGlobalTakeProfitRatio sets the "globalTakeProfitRatio" field.
func (su *StrategyUpdate) SetGlobalTakeProfitRatio(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetGlobalTakeProfitRatio(d)
	return su
}

// SetNillableGlobalTakeProfitRatio sets the "globalTakeProfitRatio" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableGlobalTakeProfitRatio(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetGlobalTakeProfitRatio(*d)
	}
	return su
}

// ClearGlobalTakeProfitRatio clears the value of the "globalTakeProfitRatio" field.
func (su *StrategyUpdate) ClearGlobalTakeProfitRatio() *StrategyUpdate {
	su.mutation.ClearGlobalTakeProfitRatio()
	return su
}

// SetDynamicStopLoss sets the "dynamicStopLoss" field.
func (su *StrategyUpdate) SetDynamicStopLoss(b bool) *StrategyUpdate {
	su.mutation.SetDynamicStopLoss(b)
	return su
}

// SetNillableDynamicStopLoss sets the "dynamicStopLoss" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableDynamicStopLoss(b *bool) *StrategyUpdate {
	if b != nil {
		su.SetDynamicStopLoss(*b)
	}
	return su
}

// ClearDynamicStopLoss clears the value of the "dynamicStopLoss" field.
func (su *StrategyUpdate) ClearDynamicStopLoss() *StrategyUpdate {
	su.mutation.ClearDynamicStopLoss()
	return su
}

// SetDropOn sets the "dropOn" field.
func (su *StrategyUpdate) SetDropOn(b bool) *StrategyUpdate {
	su.mutation.SetDropOn(b)
	return su
}

// SetNillableDropOn sets the "dropOn" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableDropOn(b *bool) *StrategyUpdate {
	if b != nil {
		su.SetDropOn(*b)
	}
	return su
}

// ClearDropOn clears the value of the "dropOn" field.
func (su *StrategyUpdate) ClearDropOn() *StrategyUpdate {
	su.mutation.ClearDropOn()
	return su
}

// SetCandlesToCheck sets the "candlesToCheck" field.
func (su *StrategyUpdate) SetCandlesToCheck(i int) *StrategyUpdate {
	su.mutation.ResetCandlesToCheck()
	su.mutation.SetCandlesToCheck(i)
	return su
}

// SetNillableCandlesToCheck sets the "candlesToCheck" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableCandlesToCheck(i *int) *StrategyUpdate {
	if i != nil {
		su.SetCandlesToCheck(*i)
	}
	return su
}

// AddCandlesToCheck adds i to the "candlesToCheck" field.
func (su *StrategyUpdate) AddCandlesToCheck(i int) *StrategyUpdate {
	su.mutation.AddCandlesToCheck(i)
	return su
}

// ClearCandlesToCheck clears the value of the "candlesToCheck" field.
func (su *StrategyUpdate) ClearCandlesToCheck() *StrategyUpdate {
	su.mutation.ClearCandlesToCheck()
	return su
}

// SetDropThreshold sets the "dropThreshold" field.
func (su *StrategyUpdate) SetDropThreshold(d decimal.Decimal) *StrategyUpdate {
	su.mutation.SetDropThreshold(d)
	return su
}

// SetNillableDropThreshold sets the "dropThreshold" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableDropThreshold(d *decimal.Decimal) *StrategyUpdate {
	if d != nil {
		su.SetDropThreshold(*d)
	}
	return su
}

// ClearDropThreshold clears the value of the "dropThreshold" field.
func (su *StrategyUpdate) ClearDropThreshold() *StrategyUpdate {
	su.mutation.ClearDropThreshold()
	return su
}

// SetEnableAutoBuy sets the "enableAutoBuy" field.
func (su *StrategyUpdate) SetEnableAutoBuy(b bool) *StrategyUpdate {
	su.mutation.SetEnableAutoBuy(b)
	return su
}

// SetNillableEnableAutoBuy sets the "enableAutoBuy" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableEnableAutoBuy(b *bool) *StrategyUpdate {
	if b != nil {
		su.SetEnableAutoBuy(*b)
	}
	return su
}

// SetEnableAutoSell sets the "enableAutoSell" field.
func (su *StrategyUpdate) SetEnableAutoSell(b bool) *StrategyUpdate {
	su.mutation.SetEnableAutoSell(b)
	return su
}

// SetNillableEnableAutoSell sets the "enableAutoSell" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableEnableAutoSell(b *bool) *StrategyUpdate {
	if b != nil {
		su.SetEnableAutoSell(*b)
	}
	return su
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (su *StrategyUpdate) SetEnableAutoExit(b bool) *StrategyUpdate {
	su.mutation.SetEnableAutoExit(b)
	return su
}

// SetNillableEnableAutoExit sets the "enableAutoExit" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableEnableAutoExit(b *bool) *StrategyUpdate {
	if b != nil {
		su.SetEnableAutoExit(*b)
	}
	return su
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (su *StrategyUpdate) SetEnablePushNotification(b bool) *StrategyUpdate {
	su.mutation.SetEnablePushNotification(b)
	return su
}

// SetNillableEnablePushNotification sets the "enablePushNotification" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableEnablePushNotification(b *bool) *StrategyUpdate {
	if b != nil {
		su.SetEnablePushNotification(*b)
	}
	return su
}

// SetStatus sets the "status" field.
func (su *StrategyUpdate) SetStatus(s strategy.Status) *StrategyUpdate {
	su.mutation.SetStatus(s)
	return su
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableStatus(s *strategy.Status) *StrategyUpdate {
	if s != nil {
		su.SetStatus(*s)
	}
	return su
}

// SetGridTrend sets the "gridTrend" field.
func (su *StrategyUpdate) SetGridTrend(s string) *StrategyUpdate {
	su.mutation.SetGridTrend(s)
	return su
}

// SetNillableGridTrend sets the "gridTrend" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableGridTrend(s *string) *StrategyUpdate {
	if s != nil {
		su.SetGridTrend(*s)
	}
	return su
}

// ClearGridTrend clears the value of the "gridTrend" field.
func (su *StrategyUpdate) ClearGridTrend() *StrategyUpdate {
	su.mutation.ClearGridTrend()
	return su
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (su *StrategyUpdate) SetLastLowerThresholdAlertTime(t time.Time) *StrategyUpdate {
	su.mutation.SetLastLowerThresholdAlertTime(t)
	return su
}

// SetNillableLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableLastLowerThresholdAlertTime(t *time.Time) *StrategyUpdate {
	if t != nil {
		su.SetLastLowerThresholdAlertTime(*t)
	}
	return su
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (su *StrategyUpdate) ClearLastLowerThresholdAlertTime() *StrategyUpdate {
	su.mutation.ClearLastLowerThresholdAlertTime()
	return su
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (su *StrategyUpdate) SetLastUpperThresholdAlertTime(t time.Time) *StrategyUpdate {
	su.mutation.SetLastUpperThresholdAlertTime(t)
	return su
}

// SetNillableLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field if the given value is not nil.
func (su *StrategyUpdate) SetNillableLastUpperThresholdAlertTime(t *time.Time) *StrategyUpdate {
	if t != nil {
		su.SetLastUpperThresholdAlertTime(*t)
	}
	return su
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (su *StrategyUpdate) ClearLastUpperThresholdAlertTime() *StrategyUpdate {
	su.mutation.ClearLastUpperThresholdAlertTime()
	return su
}

// Mutation returns the StrategyMutation object of the builder.
func (su *StrategyUpdate) Mutation() *StrategyMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StrategyUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StrategyUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StrategyUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *StrategyUpdate) defaults() {
	if _, ok := su.mutation.UpdateTime(); !ok {
		v := strategy.UpdateDefaultUpdateTime()
		su.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *StrategyUpdate) check() error {
	if v, ok := su.mutation.GUID(); ok {
		if err := strategy.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Strategy.guid": %w`, err)}
		}
	}
	if v, ok := su.mutation.Token(); ok {
		if err := strategy.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Strategy.token": %w`, err)}
		}
	}
	if v, ok := su.mutation.Symbol(); ok {
		if err := strategy.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Strategy.symbol": %w`, err)}
		}
	}
	if v, ok := su.mutation.MartinFactor(); ok {
		if err := strategy.MartinFactorValidator(v); err != nil {
			return &ValidationError{Name: "martinFactor", err: fmt.Errorf(`ent: validator failed for field "Strategy.martinFactor": %w`, err)}
		}
	}
	if v, ok := su.mutation.MaxGridLimit(); ok {
		if err := strategy.MaxGridLimitValidator(v); err != nil {
			return &ValidationError{Name: "maxGridLimit", err: fmt.Errorf(`ent: validator failed for field "Strategy.maxGridLimit": %w`, err)}
		}
	}
	if v, ok := su.mutation.Status(); ok {
		if err := strategy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Strategy.status": %w`, err)}
		}
	}
	return nil
}

func (su *StrategyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdateTime(); ok {
		_spec.SetField(strategy.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := su.mutation.GUID(); ok {
		_spec.SetField(strategy.FieldGUID, field.TypeString, value)
	}
	if value, ok := su.mutation.UserId(); ok {
		_spec.SetField(strategy.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedUserId(); ok {
		_spec.AddField(strategy.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := su.mutation.Token(); ok {
		_spec.SetField(strategy.FieldToken, field.TypeString, value)
	}
	if value, ok := su.mutation.Symbol(); ok {
		_spec.SetField(strategy.FieldSymbol, field.TypeString, value)
	}
	if value, ok := su.mutation.MartinFactor(); ok {
		_spec.SetField(strategy.FieldMartinFactor, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedMartinFactor(); ok {
		_spec.AddField(strategy.FieldMartinFactor, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.MaxGridLimit(); ok {
		_spec.SetField(strategy.FieldMaxGridLimit, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedMaxGridLimit(); ok {
		_spec.AddField(strategy.FieldMaxGridLimit, field.TypeInt, value)
	}
	if su.mutation.MaxGridLimitCleared() {
		_spec.ClearField(strategy.FieldMaxGridLimit, field.TypeInt)
	}
	if value, ok := su.mutation.TakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldTakeProfitRatio, field.TypeString, value)
	}
	if value, ok := su.mutation.UpperPriceBound(); ok {
		_spec.SetField(strategy.FieldUpperPriceBound, field.TypeString, value)
	}
	if value, ok := su.mutation.LowerPriceBound(); ok {
		_spec.SetField(strategy.FieldLowerPriceBound, field.TypeString, value)
	}
	if value, ok := su.mutation.InitialOrderSize(); ok {
		_spec.SetField(strategy.FieldInitialOrderSize, field.TypeString, value)
	}
	if value, ok := su.mutation.LastKlineVolume(); ok {
		_spec.SetField(strategy.FieldLastKlineVolume, field.TypeString, value)
	}
	if su.mutation.LastKlineVolumeCleared() {
		_spec.ClearField(strategy.FieldLastKlineVolume, field.TypeString)
	}
	if value, ok := su.mutation.FiveKlineVolume(); ok {
		_spec.SetField(strategy.FieldFiveKlineVolume, field.TypeString, value)
	}
	if su.mutation.FiveKlineVolumeCleared() {
		_spec.ClearField(strategy.FieldFiveKlineVolume, field.TypeString)
	}
	if value, ok := su.mutation.FirstOrderId(); ok {
		_spec.SetField(strategy.FieldFirstOrderId, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedFirstOrderId(); ok {
		_spec.AddField(strategy.FieldFirstOrderId, field.TypeInt, value)
	}
	if su.mutation.FirstOrderIdCleared() {
		_spec.ClearField(strategy.FieldFirstOrderId, field.TypeInt)
	}
	if value, ok := su.mutation.UpperBoundExit(); ok {
		_spec.SetField(strategy.FieldUpperBoundExit, field.TypeString, value)
	}
	if su.mutation.UpperBoundExitCleared() {
		_spec.ClearField(strategy.FieldUpperBoundExit, field.TypeString)
	}
	if value, ok := su.mutation.StopLossExit(); ok {
		_spec.SetField(strategy.FieldStopLossExit, field.TypeString, value)
	}
	if su.mutation.StopLossExitCleared() {
		_spec.ClearField(strategy.FieldStopLossExit, field.TypeString)
	}
	if value, ok := su.mutation.TakeProfitExit(); ok {
		_spec.SetField(strategy.FieldTakeProfitExit, field.TypeString, value)
	}
	if su.mutation.TakeProfitExitCleared() {
		_spec.ClearField(strategy.FieldTakeProfitExit, field.TypeString)
	}
	if value, ok := su.mutation.GlobalTakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldGlobalTakeProfitRatio, field.TypeString, value)
	}
	if su.mutation.GlobalTakeProfitRatioCleared() {
		_spec.ClearField(strategy.FieldGlobalTakeProfitRatio, field.TypeString)
	}
	if value, ok := su.mutation.DynamicStopLoss(); ok {
		_spec.SetField(strategy.FieldDynamicStopLoss, field.TypeBool, value)
	}
	if su.mutation.DynamicStopLossCleared() {
		_spec.ClearField(strategy.FieldDynamicStopLoss, field.TypeBool)
	}
	if value, ok := su.mutation.DropOn(); ok {
		_spec.SetField(strategy.FieldDropOn, field.TypeBool, value)
	}
	if su.mutation.DropOnCleared() {
		_spec.ClearField(strategy.FieldDropOn, field.TypeBool)
	}
	if value, ok := su.mutation.CandlesToCheck(); ok {
		_spec.SetField(strategy.FieldCandlesToCheck, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCandlesToCheck(); ok {
		_spec.AddField(strategy.FieldCandlesToCheck, field.TypeInt, value)
	}
	if su.mutation.CandlesToCheckCleared() {
		_spec.ClearField(strategy.FieldCandlesToCheck, field.TypeInt)
	}
	if value, ok := su.mutation.DropThreshold(); ok {
		_spec.SetField(strategy.FieldDropThreshold, field.TypeString, value)
	}
	if su.mutation.DropThresholdCleared() {
		_spec.ClearField(strategy.FieldDropThreshold, field.TypeString)
	}
	if value, ok := su.mutation.EnableAutoBuy(); ok {
		_spec.SetField(strategy.FieldEnableAutoBuy, field.TypeBool, value)
	}
	if value, ok := su.mutation.EnableAutoSell(); ok {
		_spec.SetField(strategy.FieldEnableAutoSell, field.TypeBool, value)
	}
	if value, ok := su.mutation.EnableAutoExit(); ok {
		_spec.SetField(strategy.FieldEnableAutoExit, field.TypeBool, value)
	}
	if value, ok := su.mutation.EnablePushNotification(); ok {
		_spec.SetField(strategy.FieldEnablePushNotification, field.TypeBool, value)
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.SetField(strategy.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := su.mutation.GridTrend(); ok {
		_spec.SetField(strategy.FieldGridTrend, field.TypeString, value)
	}
	if su.mutation.GridTrendCleared() {
		_spec.ClearField(strategy.FieldGridTrend, field.TypeString)
	}
	if value, ok := su.mutation.LastLowerThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime, value)
	}
	if su.mutation.LastLowerThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime)
	}
	if value, ok := su.mutation.LastUpperThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime, value)
	}
	if su.mutation.LastUpperThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StrategyUpdateOne is the builder for updating a single Strategy entity.
type StrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyMutation
}

// SetUpdateTime sets the "update_time" field.
func (suo *StrategyUpdateOne) SetUpdateTime(t time.Time) *StrategyUpdateOne {
	suo.mutation.SetUpdateTime(t)
	return suo
}

// SetGUID sets the "guid" field.
func (suo *StrategyUpdateOne) SetGUID(s string) *StrategyUpdateOne {
	suo.mutation.SetGUID(s)
	return suo
}

// SetNillableGUID sets the "guid" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableGUID(s *string) *StrategyUpdateOne {
	if s != nil {
		suo.SetGUID(*s)
	}
	return suo
}

// SetUserId sets the "userId" field.
func (suo *StrategyUpdateOne) SetUserId(i int64) *StrategyUpdateOne {
	suo.mutation.ResetUserId()
	suo.mutation.SetUserId(i)
	return suo
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableUserId(i *int64) *StrategyUpdateOne {
	if i != nil {
		suo.SetUserId(*i)
	}
	return suo
}

// AddUserId adds i to the "userId" field.
func (suo *StrategyUpdateOne) AddUserId(i int64) *StrategyUpdateOne {
	suo.mutation.AddUserId(i)
	return suo
}

// SetToken sets the "token" field.
func (suo *StrategyUpdateOne) SetToken(s string) *StrategyUpdateOne {
	suo.mutation.SetToken(s)
	return suo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableToken(s *string) *StrategyUpdateOne {
	if s != nil {
		suo.SetToken(*s)
	}
	return suo
}

// SetSymbol sets the "symbol" field.
func (suo *StrategyUpdateOne) SetSymbol(s string) *StrategyUpdateOne {
	suo.mutation.SetSymbol(s)
	return suo
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableSymbol(s *string) *StrategyUpdateOne {
	if s != nil {
		suo.SetSymbol(*s)
	}
	return suo
}

// SetMartinFactor sets the "martinFactor" field.
func (suo *StrategyUpdateOne) SetMartinFactor(f float64) *StrategyUpdateOne {
	suo.mutation.ResetMartinFactor()
	suo.mutation.SetMartinFactor(f)
	return suo
}

// SetNillableMartinFactor sets the "martinFactor" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableMartinFactor(f *float64) *StrategyUpdateOne {
	if f != nil {
		suo.SetMartinFactor(*f)
	}
	return suo
}

// AddMartinFactor adds f to the "martinFactor" field.
func (suo *StrategyUpdateOne) AddMartinFactor(f float64) *StrategyUpdateOne {
	suo.mutation.AddMartinFactor(f)
	return suo
}

// SetMaxGridLimit sets the "maxGridLimit" field.
func (suo *StrategyUpdateOne) SetMaxGridLimit(i int) *StrategyUpdateOne {
	suo.mutation.ResetMaxGridLimit()
	suo.mutation.SetMaxGridLimit(i)
	return suo
}

// SetNillableMaxGridLimit sets the "maxGridLimit" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableMaxGridLimit(i *int) *StrategyUpdateOne {
	if i != nil {
		suo.SetMaxGridLimit(*i)
	}
	return suo
}

// AddMaxGridLimit adds i to the "maxGridLimit" field.
func (suo *StrategyUpdateOne) AddMaxGridLimit(i int) *StrategyUpdateOne {
	suo.mutation.AddMaxGridLimit(i)
	return suo
}

// ClearMaxGridLimit clears the value of the "maxGridLimit" field.
func (suo *StrategyUpdateOne) ClearMaxGridLimit() *StrategyUpdateOne {
	suo.mutation.ClearMaxGridLimit()
	return suo
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (suo *StrategyUpdateOne) SetTakeProfitRatio(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetTakeProfitRatio(d)
	return suo
}

// SetNillableTakeProfitRatio sets the "takeProfitRatio" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableTakeProfitRatio(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetTakeProfitRatio(*d)
	}
	return suo
}

// SetUpperPriceBound sets the "upperPriceBound" field.
func (suo *StrategyUpdateOne) SetUpperPriceBound(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetUpperPriceBound(d)
	return suo
}

// SetNillableUpperPriceBound sets the "upperPriceBound" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableUpperPriceBound(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetUpperPriceBound(*d)
	}
	return suo
}

// SetLowerPriceBound sets the "lowerPriceBound" field.
func (suo *StrategyUpdateOne) SetLowerPriceBound(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetLowerPriceBound(d)
	return suo
}

// SetNillableLowerPriceBound sets the "lowerPriceBound" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableLowerPriceBound(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetLowerPriceBound(*d)
	}
	return suo
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (suo *StrategyUpdateOne) SetInitialOrderSize(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetInitialOrderSize(d)
	return suo
}

// SetNillableInitialOrderSize sets the "initialOrderSize" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableInitialOrderSize(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetInitialOrderSize(*d)
	}
	return suo
}

// SetLastKlineVolume sets the "lastKlineVolume" field.
func (suo *StrategyUpdateOne) SetLastKlineVolume(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetLastKlineVolume(d)
	return suo
}

// SetNillableLastKlineVolume sets the "lastKlineVolume" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableLastKlineVolume(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetLastKlineVolume(*d)
	}
	return suo
}

// ClearLastKlineVolume clears the value of the "lastKlineVolume" field.
func (suo *StrategyUpdateOne) ClearLastKlineVolume() *StrategyUpdateOne {
	suo.mutation.ClearLastKlineVolume()
	return suo
}

// SetFiveKlineVolume sets the "fiveKlineVolume" field.
func (suo *StrategyUpdateOne) SetFiveKlineVolume(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetFiveKlineVolume(d)
	return suo
}

// SetNillableFiveKlineVolume sets the "fiveKlineVolume" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableFiveKlineVolume(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetFiveKlineVolume(*d)
	}
	return suo
}

// ClearFiveKlineVolume clears the value of the "fiveKlineVolume" field.
func (suo *StrategyUpdateOne) ClearFiveKlineVolume() *StrategyUpdateOne {
	suo.mutation.ClearFiveKlineVolume()
	return suo
}

// SetFirstOrderId sets the "firstOrderId" field.
func (suo *StrategyUpdateOne) SetFirstOrderId(i int) *StrategyUpdateOne {
	suo.mutation.ResetFirstOrderId()
	suo.mutation.SetFirstOrderId(i)
	return suo
}

// SetNillableFirstOrderId sets the "firstOrderId" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableFirstOrderId(i *int) *StrategyUpdateOne {
	if i != nil {
		suo.SetFirstOrderId(*i)
	}
	return suo
}

// AddFirstOrderId adds i to the "firstOrderId" field.
func (suo *StrategyUpdateOne) AddFirstOrderId(i int) *StrategyUpdateOne {
	suo.mutation.AddFirstOrderId(i)
	return suo
}

// ClearFirstOrderId clears the value of the "firstOrderId" field.
func (suo *StrategyUpdateOne) ClearFirstOrderId() *StrategyUpdateOne {
	suo.mutation.ClearFirstOrderId()
	return suo
}

// SetUpperBoundExit sets the "upperBoundExit" field.
func (suo *StrategyUpdateOne) SetUpperBoundExit(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetUpperBoundExit(d)
	return suo
}

// SetNillableUpperBoundExit sets the "upperBoundExit" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableUpperBoundExit(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetUpperBoundExit(*d)
	}
	return suo
}

// ClearUpperBoundExit clears the value of the "upperBoundExit" field.
func (suo *StrategyUpdateOne) ClearUpperBoundExit() *StrategyUpdateOne {
	suo.mutation.ClearUpperBoundExit()
	return suo
}

// SetStopLossExit sets the "stopLossExit" field.
func (suo *StrategyUpdateOne) SetStopLossExit(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetStopLossExit(d)
	return suo
}

// SetNillableStopLossExit sets the "stopLossExit" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableStopLossExit(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetStopLossExit(*d)
	}
	return suo
}

// ClearStopLossExit clears the value of the "stopLossExit" field.
func (suo *StrategyUpdateOne) ClearStopLossExit() *StrategyUpdateOne {
	suo.mutation.ClearStopLossExit()
	return suo
}

// SetTakeProfitExit sets the "takeProfitExit" field.
func (suo *StrategyUpdateOne) SetTakeProfitExit(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetTakeProfitExit(d)
	return suo
}

// SetNillableTakeProfitExit sets the "takeProfitExit" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableTakeProfitExit(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetTakeProfitExit(*d)
	}
	return suo
}

// ClearTakeProfitExit clears the value of the "takeProfitExit" field.
func (suo *StrategyUpdateOne) ClearTakeProfitExit() *StrategyUpdateOne {
	suo.mutation.ClearTakeProfitExit()
	return suo
}

// SetGlobalTakeProfitRatio sets the "globalTakeProfitRatio" field.
func (suo *StrategyUpdateOne) SetGlobalTakeProfitRatio(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetGlobalTakeProfitRatio(d)
	return suo
}

// SetNillableGlobalTakeProfitRatio sets the "globalTakeProfitRatio" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableGlobalTakeProfitRatio(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetGlobalTakeProfitRatio(*d)
	}
	return suo
}

// ClearGlobalTakeProfitRatio clears the value of the "globalTakeProfitRatio" field.
func (suo *StrategyUpdateOne) ClearGlobalTakeProfitRatio() *StrategyUpdateOne {
	suo.mutation.ClearGlobalTakeProfitRatio()
	return suo
}

// SetDynamicStopLoss sets the "dynamicStopLoss" field.
func (suo *StrategyUpdateOne) SetDynamicStopLoss(b bool) *StrategyUpdateOne {
	suo.mutation.SetDynamicStopLoss(b)
	return suo
}

// SetNillableDynamicStopLoss sets the "dynamicStopLoss" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableDynamicStopLoss(b *bool) *StrategyUpdateOne {
	if b != nil {
		suo.SetDynamicStopLoss(*b)
	}
	return suo
}

// ClearDynamicStopLoss clears the value of the "dynamicStopLoss" field.
func (suo *StrategyUpdateOne) ClearDynamicStopLoss() *StrategyUpdateOne {
	suo.mutation.ClearDynamicStopLoss()
	return suo
}

// SetDropOn sets the "dropOn" field.
func (suo *StrategyUpdateOne) SetDropOn(b bool) *StrategyUpdateOne {
	suo.mutation.SetDropOn(b)
	return suo
}

// SetNillableDropOn sets the "dropOn" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableDropOn(b *bool) *StrategyUpdateOne {
	if b != nil {
		suo.SetDropOn(*b)
	}
	return suo
}

// ClearDropOn clears the value of the "dropOn" field.
func (suo *StrategyUpdateOne) ClearDropOn() *StrategyUpdateOne {
	suo.mutation.ClearDropOn()
	return suo
}

// SetCandlesToCheck sets the "candlesToCheck" field.
func (suo *StrategyUpdateOne) SetCandlesToCheck(i int) *StrategyUpdateOne {
	suo.mutation.ResetCandlesToCheck()
	suo.mutation.SetCandlesToCheck(i)
	return suo
}

// SetNillableCandlesToCheck sets the "candlesToCheck" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableCandlesToCheck(i *int) *StrategyUpdateOne {
	if i != nil {
		suo.SetCandlesToCheck(*i)
	}
	return suo
}

// AddCandlesToCheck adds i to the "candlesToCheck" field.
func (suo *StrategyUpdateOne) AddCandlesToCheck(i int) *StrategyUpdateOne {
	suo.mutation.AddCandlesToCheck(i)
	return suo
}

// ClearCandlesToCheck clears the value of the "candlesToCheck" field.
func (suo *StrategyUpdateOne) ClearCandlesToCheck() *StrategyUpdateOne {
	suo.mutation.ClearCandlesToCheck()
	return suo
}

// SetDropThreshold sets the "dropThreshold" field.
func (suo *StrategyUpdateOne) SetDropThreshold(d decimal.Decimal) *StrategyUpdateOne {
	suo.mutation.SetDropThreshold(d)
	return suo
}

// SetNillableDropThreshold sets the "dropThreshold" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableDropThreshold(d *decimal.Decimal) *StrategyUpdateOne {
	if d != nil {
		suo.SetDropThreshold(*d)
	}
	return suo
}

// ClearDropThreshold clears the value of the "dropThreshold" field.
func (suo *StrategyUpdateOne) ClearDropThreshold() *StrategyUpdateOne {
	suo.mutation.ClearDropThreshold()
	return suo
}

// SetEnableAutoBuy sets the "enableAutoBuy" field.
func (suo *StrategyUpdateOne) SetEnableAutoBuy(b bool) *StrategyUpdateOne {
	suo.mutation.SetEnableAutoBuy(b)
	return suo
}

// SetNillableEnableAutoBuy sets the "enableAutoBuy" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableEnableAutoBuy(b *bool) *StrategyUpdateOne {
	if b != nil {
		suo.SetEnableAutoBuy(*b)
	}
	return suo
}

// SetEnableAutoSell sets the "enableAutoSell" field.
func (suo *StrategyUpdateOne) SetEnableAutoSell(b bool) *StrategyUpdateOne {
	suo.mutation.SetEnableAutoSell(b)
	return suo
}

// SetNillableEnableAutoSell sets the "enableAutoSell" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableEnableAutoSell(b *bool) *StrategyUpdateOne {
	if b != nil {
		suo.SetEnableAutoSell(*b)
	}
	return suo
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (suo *StrategyUpdateOne) SetEnableAutoExit(b bool) *StrategyUpdateOne {
	suo.mutation.SetEnableAutoExit(b)
	return suo
}

// SetNillableEnableAutoExit sets the "enableAutoExit" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableEnableAutoExit(b *bool) *StrategyUpdateOne {
	if b != nil {
		suo.SetEnableAutoExit(*b)
	}
	return suo
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (suo *StrategyUpdateOne) SetEnablePushNotification(b bool) *StrategyUpdateOne {
	suo.mutation.SetEnablePushNotification(b)
	return suo
}

// SetNillableEnablePushNotification sets the "enablePushNotification" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableEnablePushNotification(b *bool) *StrategyUpdateOne {
	if b != nil {
		suo.SetEnablePushNotification(*b)
	}
	return suo
}

// SetStatus sets the "status" field.
func (suo *StrategyUpdateOne) SetStatus(s strategy.Status) *StrategyUpdateOne {
	suo.mutation.SetStatus(s)
	return suo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableStatus(s *strategy.Status) *StrategyUpdateOne {
	if s != nil {
		suo.SetStatus(*s)
	}
	return suo
}

// SetGridTrend sets the "gridTrend" field.
func (suo *StrategyUpdateOne) SetGridTrend(s string) *StrategyUpdateOne {
	suo.mutation.SetGridTrend(s)
	return suo
}

// SetNillableGridTrend sets the "gridTrend" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableGridTrend(s *string) *StrategyUpdateOne {
	if s != nil {
		suo.SetGridTrend(*s)
	}
	return suo
}

// ClearGridTrend clears the value of the "gridTrend" field.
func (suo *StrategyUpdateOne) ClearGridTrend() *StrategyUpdateOne {
	suo.mutation.ClearGridTrend()
	return suo
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (suo *StrategyUpdateOne) SetLastLowerThresholdAlertTime(t time.Time) *StrategyUpdateOne {
	suo.mutation.SetLastLowerThresholdAlertTime(t)
	return suo
}

// SetNillableLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableLastLowerThresholdAlertTime(t *time.Time) *StrategyUpdateOne {
	if t != nil {
		suo.SetLastLowerThresholdAlertTime(*t)
	}
	return suo
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (suo *StrategyUpdateOne) ClearLastLowerThresholdAlertTime() *StrategyUpdateOne {
	suo.mutation.ClearLastLowerThresholdAlertTime()
	return suo
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (suo *StrategyUpdateOne) SetLastUpperThresholdAlertTime(t time.Time) *StrategyUpdateOne {
	suo.mutation.SetLastUpperThresholdAlertTime(t)
	return suo
}

// SetNillableLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field if the given value is not nil.
func (suo *StrategyUpdateOne) SetNillableLastUpperThresholdAlertTime(t *time.Time) *StrategyUpdateOne {
	if t != nil {
		suo.SetLastUpperThresholdAlertTime(*t)
	}
	return suo
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (suo *StrategyUpdateOne) ClearLastUpperThresholdAlertTime() *StrategyUpdateOne {
	suo.mutation.ClearLastUpperThresholdAlertTime()
	return suo
}

// Mutation returns the StrategyMutation object of the builder.
func (suo *StrategyUpdateOne) Mutation() *StrategyMutation {
	return suo.mutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (suo *StrategyUpdateOne) Where(ps ...predicate.Strategy) *StrategyUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StrategyUpdateOne) Select(field string, fields ...string) *StrategyUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Strategy entity.
func (suo *StrategyUpdateOne) Save(ctx context.Context) (*Strategy, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StrategyUpdateOne) SaveX(ctx context.Context) *Strategy {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StrategyUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *StrategyUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdateTime(); !ok {
		v := strategy.UpdateDefaultUpdateTime()
		suo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *StrategyUpdateOne) check() error {
	if v, ok := suo.mutation.GUID(); ok {
		if err := strategy.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Strategy.guid": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Token(); ok {
		if err := strategy.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Strategy.token": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Symbol(); ok {
		if err := strategy.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Strategy.symbol": %w`, err)}
		}
	}
	if v, ok := suo.mutation.MartinFactor(); ok {
		if err := strategy.MartinFactorValidator(v); err != nil {
			return &ValidationError{Name: "martinFactor", err: fmt.Errorf(`ent: validator failed for field "Strategy.martinFactor": %w`, err)}
		}
	}
	if v, ok := suo.mutation.MaxGridLimit(); ok {
		if err := strategy.MaxGridLimitValidator(v); err != nil {
			return &ValidationError{Name: "maxGridLimit", err: fmt.Errorf(`ent: validator failed for field "Strategy.maxGridLimit": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Status(); ok {
		if err := strategy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Strategy.status": %w`, err)}
		}
	}
	return nil
}

func (suo *StrategyUpdateOne) sqlSave(ctx context.Context) (_node *Strategy, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Strategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategy.FieldID)
		for _, f := range fields {
			if !strategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdateTime(); ok {
		_spec.SetField(strategy.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := suo.mutation.GUID(); ok {
		_spec.SetField(strategy.FieldGUID, field.TypeString, value)
	}
	if value, ok := suo.mutation.UserId(); ok {
		_spec.SetField(strategy.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedUserId(); ok {
		_spec.AddField(strategy.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.Token(); ok {
		_spec.SetField(strategy.FieldToken, field.TypeString, value)
	}
	if value, ok := suo.mutation.Symbol(); ok {
		_spec.SetField(strategy.FieldSymbol, field.TypeString, value)
	}
	if value, ok := suo.mutation.MartinFactor(); ok {
		_spec.SetField(strategy.FieldMartinFactor, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedMartinFactor(); ok {
		_spec.AddField(strategy.FieldMartinFactor, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.MaxGridLimit(); ok {
		_spec.SetField(strategy.FieldMaxGridLimit, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedMaxGridLimit(); ok {
		_spec.AddField(strategy.FieldMaxGridLimit, field.TypeInt, value)
	}
	if suo.mutation.MaxGridLimitCleared() {
		_spec.ClearField(strategy.FieldMaxGridLimit, field.TypeInt)
	}
	if value, ok := suo.mutation.TakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldTakeProfitRatio, field.TypeString, value)
	}
	if value, ok := suo.mutation.UpperPriceBound(); ok {
		_spec.SetField(strategy.FieldUpperPriceBound, field.TypeString, value)
	}
	if value, ok := suo.mutation.LowerPriceBound(); ok {
		_spec.SetField(strategy.FieldLowerPriceBound, field.TypeString, value)
	}
	if value, ok := suo.mutation.InitialOrderSize(); ok {
		_spec.SetField(strategy.FieldInitialOrderSize, field.TypeString, value)
	}
	if value, ok := suo.mutation.LastKlineVolume(); ok {
		_spec.SetField(strategy.FieldLastKlineVolume, field.TypeString, value)
	}
	if suo.mutation.LastKlineVolumeCleared() {
		_spec.ClearField(strategy.FieldLastKlineVolume, field.TypeString)
	}
	if value, ok := suo.mutation.FiveKlineVolume(); ok {
		_spec.SetField(strategy.FieldFiveKlineVolume, field.TypeString, value)
	}
	if suo.mutation.FiveKlineVolumeCleared() {
		_spec.ClearField(strategy.FieldFiveKlineVolume, field.TypeString)
	}
	if value, ok := suo.mutation.FirstOrderId(); ok {
		_spec.SetField(strategy.FieldFirstOrderId, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedFirstOrderId(); ok {
		_spec.AddField(strategy.FieldFirstOrderId, field.TypeInt, value)
	}
	if suo.mutation.FirstOrderIdCleared() {
		_spec.ClearField(strategy.FieldFirstOrderId, field.TypeInt)
	}
	if value, ok := suo.mutation.UpperBoundExit(); ok {
		_spec.SetField(strategy.FieldUpperBoundExit, field.TypeString, value)
	}
	if suo.mutation.UpperBoundExitCleared() {
		_spec.ClearField(strategy.FieldUpperBoundExit, field.TypeString)
	}
	if value, ok := suo.mutation.StopLossExit(); ok {
		_spec.SetField(strategy.FieldStopLossExit, field.TypeString, value)
	}
	if suo.mutation.StopLossExitCleared() {
		_spec.ClearField(strategy.FieldStopLossExit, field.TypeString)
	}
	if value, ok := suo.mutation.TakeProfitExit(); ok {
		_spec.SetField(strategy.FieldTakeProfitExit, field.TypeString, value)
	}
	if suo.mutation.TakeProfitExitCleared() {
		_spec.ClearField(strategy.FieldTakeProfitExit, field.TypeString)
	}
	if value, ok := suo.mutation.GlobalTakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldGlobalTakeProfitRatio, field.TypeString, value)
	}
	if suo.mutation.GlobalTakeProfitRatioCleared() {
		_spec.ClearField(strategy.FieldGlobalTakeProfitRatio, field.TypeString)
	}
	if value, ok := suo.mutation.DynamicStopLoss(); ok {
		_spec.SetField(strategy.FieldDynamicStopLoss, field.TypeBool, value)
	}
	if suo.mutation.DynamicStopLossCleared() {
		_spec.ClearField(strategy.FieldDynamicStopLoss, field.TypeBool)
	}
	if value, ok := suo.mutation.DropOn(); ok {
		_spec.SetField(strategy.FieldDropOn, field.TypeBool, value)
	}
	if suo.mutation.DropOnCleared() {
		_spec.ClearField(strategy.FieldDropOn, field.TypeBool)
	}
	if value, ok := suo.mutation.CandlesToCheck(); ok {
		_spec.SetField(strategy.FieldCandlesToCheck, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCandlesToCheck(); ok {
		_spec.AddField(strategy.FieldCandlesToCheck, field.TypeInt, value)
	}
	if suo.mutation.CandlesToCheckCleared() {
		_spec.ClearField(strategy.FieldCandlesToCheck, field.TypeInt)
	}
	if value, ok := suo.mutation.DropThreshold(); ok {
		_spec.SetField(strategy.FieldDropThreshold, field.TypeString, value)
	}
	if suo.mutation.DropThresholdCleared() {
		_spec.ClearField(strategy.FieldDropThreshold, field.TypeString)
	}
	if value, ok := suo.mutation.EnableAutoBuy(); ok {
		_spec.SetField(strategy.FieldEnableAutoBuy, field.TypeBool, value)
	}
	if value, ok := suo.mutation.EnableAutoSell(); ok {
		_spec.SetField(strategy.FieldEnableAutoSell, field.TypeBool, value)
	}
	if value, ok := suo.mutation.EnableAutoExit(); ok {
		_spec.SetField(strategy.FieldEnableAutoExit, field.TypeBool, value)
	}
	if value, ok := suo.mutation.EnablePushNotification(); ok {
		_spec.SetField(strategy.FieldEnablePushNotification, field.TypeBool, value)
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.SetField(strategy.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := suo.mutation.GridTrend(); ok {
		_spec.SetField(strategy.FieldGridTrend, field.TypeString, value)
	}
	if suo.mutation.GridTrendCleared() {
		_spec.ClearField(strategy.FieldGridTrend, field.TypeString)
	}
	if value, ok := suo.mutation.LastLowerThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime, value)
	}
	if suo.mutation.LastLowerThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime)
	}
	if value, ok := suo.mutation.LastUpperThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime, value)
	}
	if suo.mutation.LastUpperThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime)
	}
	_node = &Strategy{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
