// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/strategy"
	"github.com/shopspring/decimal"
)

// StrategyCreate is the builder for creating a Strategy entity.
type StrategyCreate struct {
	config
	mutation *StrategyMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (sc *StrategyCreate) SetCreateTime(t time.Time) *StrategyCreate {
	sc.mutation.SetCreateTime(t)
	return sc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableCreateTime(t *time.Time) *StrategyCreate {
	if t != nil {
		sc.SetCreateTime(*t)
	}
	return sc
}

// SetUpdateTime sets the "update_time" field.
func (sc *StrategyCreate) SetUpdateTime(t time.Time) *StrategyCreate {
	sc.mutation.SetUpdateTime(t)
	return sc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableUpdateTime(t *time.Time) *StrategyCreate {
	if t != nil {
		sc.SetUpdateTime(*t)
	}
	return sc
}

// SetGUID sets the "guid" field.
func (sc *StrategyCreate) SetGUID(s string) *StrategyCreate {
	sc.mutation.SetGUID(s)
	return sc
}

// SetUserId sets the "userId" field.
func (sc *StrategyCreate) SetUserId(i int64) *StrategyCreate {
	sc.mutation.SetUserId(i)
	return sc
}

// SetToken sets the "token" field.
func (sc *StrategyCreate) SetToken(s string) *StrategyCreate {
	sc.mutation.SetToken(s)
	return sc
}

// SetSymbol sets the "symbol" field.
func (sc *StrategyCreate) SetSymbol(s string) *StrategyCreate {
	sc.mutation.SetSymbol(s)
	return sc
}

// SetMartinFactor sets the "martinFactor" field.
func (sc *StrategyCreate) SetMartinFactor(f float64) *StrategyCreate {
	sc.mutation.SetMartinFactor(f)
	return sc
}

// SetMaxGridLimit sets the "maxGridLimit" field.
func (sc *StrategyCreate) SetMaxGridLimit(i int) *StrategyCreate {
	sc.mutation.SetMaxGridLimit(i)
	return sc
}

// SetNillableMaxGridLimit sets the "maxGridLimit" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableMaxGridLimit(i *int) *StrategyCreate {
	if i != nil {
		sc.SetMaxGridLimit(*i)
	}
	return sc
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (sc *StrategyCreate) SetTakeProfitRatio(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetTakeProfitRatio(d)
	return sc
}

// SetUpperPriceBound sets the "upperPriceBound" field.
func (sc *StrategyCreate) SetUpperPriceBound(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetUpperPriceBound(d)
	return sc
}

// SetLowerPriceBound sets the "lowerPriceBound" field.
func (sc *StrategyCreate) SetLowerPriceBound(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetLowerPriceBound(d)
	return sc
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (sc *StrategyCreate) SetInitialOrderSize(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetInitialOrderSize(d)
	return sc
}

// SetLastKlineVolume sets the "lastKlineVolume" field.
func (sc *StrategyCreate) SetLastKlineVolume(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetLastKlineVolume(d)
	return sc
}

// SetNillableLastKlineVolume sets the "lastKlineVolume" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableLastKlineVolume(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetLastKlineVolume(*d)
	}
	return sc
}

// SetFiveKlineVolume sets the "fiveKlineVolume" field.
func (sc *StrategyCreate) SetFiveKlineVolume(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetFiveKlineVolume(d)
	return sc
}

// SetNillableFiveKlineVolume sets the "fiveKlineVolume" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableFiveKlineVolume(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetFiveKlineVolume(*d)
	}
	return sc
}

// SetFirstOrderId sets the "firstOrderId" field.
func (sc *StrategyCreate) SetFirstOrderId(i int) *StrategyCreate {
	sc.mutation.SetFirstOrderId(i)
	return sc
}

// SetNillableFirstOrderId sets the "firstOrderId" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableFirstOrderId(i *int) *StrategyCreate {
	if i != nil {
		sc.SetFirstOrderId(*i)
	}
	return sc
}

// SetUpperBoundExit sets the "upperBoundExit" field.
func (sc *StrategyCreate) SetUpperBoundExit(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetUpperBoundExit(d)
	return sc
}

// SetNillableUpperBoundExit sets the "upperBoundExit" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableUpperBoundExit(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetUpperBoundExit(*d)
	}
	return sc
}

// SetStopLossExit sets the "stopLossExit" field.
func (sc *StrategyCreate) SetStopLossExit(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetStopLossExit(d)
	return sc
}

// SetNillableStopLossExit sets the "stopLossExit" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableStopLossExit(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetStopLossExit(*d)
	}
	return sc
}

// SetTakeProfitExit sets the "takeProfitExit" field.
func (sc *StrategyCreate) SetTakeProfitExit(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetTakeProfitExit(d)
	return sc
}

// SetNillableTakeProfitExit sets the "takeProfitExit" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableTakeProfitExit(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetTakeProfitExit(*d)
	}
	return sc
}

// SetGlobalTakeProfitRatio sets the "globalTakeProfitRatio" field.
func (sc *StrategyCreate) SetGlobalTakeProfitRatio(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetGlobalTakeProfitRatio(d)
	return sc
}

// SetNillableGlobalTakeProfitRatio sets the "globalTakeProfitRatio" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableGlobalTakeProfitRatio(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetGlobalTakeProfitRatio(*d)
	}
	return sc
}

// SetDynamicStopLoss sets the "dynamicStopLoss" field.
func (sc *StrategyCreate) SetDynamicStopLoss(b bool) *StrategyCreate {
	sc.mutation.SetDynamicStopLoss(b)
	return sc
}

// SetNillableDynamicStopLoss sets the "dynamicStopLoss" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableDynamicStopLoss(b *bool) *StrategyCreate {
	if b != nil {
		sc.SetDynamicStopLoss(*b)
	}
	return sc
}

// SetDropOn sets the "dropOn" field.
func (sc *StrategyCreate) SetDropOn(b bool) *StrategyCreate {
	sc.mutation.SetDropOn(b)
	return sc
}

// SetNillableDropOn sets the "dropOn" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableDropOn(b *bool) *StrategyCreate {
	if b != nil {
		sc.SetDropOn(*b)
	}
	return sc
}

// SetCandlesToCheck sets the "candlesToCheck" field.
func (sc *StrategyCreate) SetCandlesToCheck(i int) *StrategyCreate {
	sc.mutation.SetCandlesToCheck(i)
	return sc
}

// SetNillableCandlesToCheck sets the "candlesToCheck" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableCandlesToCheck(i *int) *StrategyCreate {
	if i != nil {
		sc.SetCandlesToCheck(*i)
	}
	return sc
}

// SetDropThreshold sets the "dropThreshold" field.
func (sc *StrategyCreate) SetDropThreshold(d decimal.Decimal) *StrategyCreate {
	sc.mutation.SetDropThreshold(d)
	return sc
}

// SetNillableDropThreshold sets the "dropThreshold" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableDropThreshold(d *decimal.Decimal) *StrategyCreate {
	if d != nil {
		sc.SetDropThreshold(*d)
	}
	return sc
}

// SetEnableAutoBuy sets the "enableAutoBuy" field.
func (sc *StrategyCreate) SetEnableAutoBuy(b bool) *StrategyCreate {
	sc.mutation.SetEnableAutoBuy(b)
	return sc
}

// SetEnableAutoSell sets the "enableAutoSell" field.
func (sc *StrategyCreate) SetEnableAutoSell(b bool) *StrategyCreate {
	sc.mutation.SetEnableAutoSell(b)
	return sc
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (sc *StrategyCreate) SetEnableAutoExit(b bool) *StrategyCreate {
	sc.mutation.SetEnableAutoExit(b)
	return sc
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (sc *StrategyCreate) SetEnablePushNotification(b bool) *StrategyCreate {
	sc.mutation.SetEnablePushNotification(b)
	return sc
}

// SetStatus sets the "status" field.
func (sc *StrategyCreate) SetStatus(s strategy.Status) *StrategyCreate {
	sc.mutation.SetStatus(s)
	return sc
}

// SetGridTrend sets the "gridTrend" field.
func (sc *StrategyCreate) SetGridTrend(s string) *StrategyCreate {
	sc.mutation.SetGridTrend(s)
	return sc
}

// SetNillableGridTrend sets the "gridTrend" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableGridTrend(s *string) *StrategyCreate {
	if s != nil {
		sc.SetGridTrend(*s)
	}
	return sc
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (sc *StrategyCreate) SetLastLowerThresholdAlertTime(t time.Time) *StrategyCreate {
	sc.mutation.SetLastLowerThresholdAlertTime(t)
	return sc
}

// SetNillableLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableLastLowerThresholdAlertTime(t *time.Time) *StrategyCreate {
	if t != nil {
		sc.SetLastLowerThresholdAlertTime(*t)
	}
	return sc
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (sc *StrategyCreate) SetLastUpperThresholdAlertTime(t time.Time) *StrategyCreate {
	sc.mutation.SetLastUpperThresholdAlertTime(t)
	return sc
}

// SetNillableLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field if the given value is not nil.
func (sc *StrategyCreate) SetNillableLastUpperThresholdAlertTime(t *time.Time) *StrategyCreate {
	if t != nil {
		sc.SetLastUpperThresholdAlertTime(*t)
	}
	return sc
}

// Mutation returns the StrategyMutation object of the builder.
func (sc *StrategyCreate) Mutation() *StrategyMutation {
	return sc.mutation
}

// Save creates the Strategy in the database.
func (sc *StrategyCreate) Save(ctx context.Context) (*Strategy, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StrategyCreate) SaveX(ctx context.Context) *Strategy {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StrategyCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StrategyCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StrategyCreate) defaults() {
	if _, ok := sc.mutation.CreateTime(); !ok {
		v := strategy.DefaultCreateTime()
		sc.mutation.SetCreateTime(v)
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		v := strategy.DefaultUpdateTime()
		sc.mutation.SetUpdateTime(v)
	}
	if _, ok := sc.mutation.CandlesToCheck(); !ok {
		v := strategy.DefaultCandlesToCheck
		sc.mutation.SetCandlesToCheck(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StrategyCreate) check() error {
	if _, ok := sc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Strategy.create_time"`)}
	}
	if _, ok := sc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Strategy.update_time"`)}
	}
	if _, ok := sc.mutation.GUID(); !ok {
		return &ValidationError{Name: "guid", err: errors.New(`ent: missing required field "Strategy.guid"`)}
	}
	if v, ok := sc.mutation.GUID(); ok {
		if err := strategy.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Strategy.guid": %w`, err)}
		}
	}
	if _, ok := sc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "Strategy.userId"`)}
	}
	if _, ok := sc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Strategy.token"`)}
	}
	if v, ok := sc.mutation.Token(); ok {
		if err := strategy.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Strategy.token": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "Strategy.symbol"`)}
	}
	if v, ok := sc.mutation.Symbol(); ok {
		if err := strategy.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Strategy.symbol": %w`, err)}
		}
	}
	if _, ok := sc.mutation.MartinFactor(); !ok {
		return &ValidationError{Name: "martinFactor", err: errors.New(`ent: missing required field "Strategy.martinFactor"`)}
	}
	if v, ok := sc.mutation.MartinFactor(); ok {
		if err := strategy.MartinFactorValidator(v); err != nil {
			return &ValidationError{Name: "martinFactor", err: fmt.Errorf(`ent: validator failed for field "Strategy.martinFactor": %w`, err)}
		}
	}
	if v, ok := sc.mutation.MaxGridLimit(); ok {
		if err := strategy.MaxGridLimitValidator(v); err != nil {
			return &ValidationError{Name: "maxGridLimit", err: fmt.Errorf(`ent: validator failed for field "Strategy.maxGridLimit": %w`, err)}
		}
	}
	if _, ok := sc.mutation.TakeProfitRatio(); !ok {
		return &ValidationError{Name: "takeProfitRatio", err: errors.New(`ent: missing required field "Strategy.takeProfitRatio"`)}
	}
	if _, ok := sc.mutation.UpperPriceBound(); !ok {
		return &ValidationError{Name: "upperPriceBound", err: errors.New(`ent: missing required field "Strategy.upperPriceBound"`)}
	}
	if _, ok := sc.mutation.LowerPriceBound(); !ok {
		return &ValidationError{Name: "lowerPriceBound", err: errors.New(`ent: missing required field "Strategy.lowerPriceBound"`)}
	}
	if _, ok := sc.mutation.InitialOrderSize(); !ok {
		return &ValidationError{Name: "initialOrderSize", err: errors.New(`ent: missing required field "Strategy.initialOrderSize"`)}
	}
	if _, ok := sc.mutation.EnableAutoBuy(); !ok {
		return &ValidationError{Name: "enableAutoBuy", err: errors.New(`ent: missing required field "Strategy.enableAutoBuy"`)}
	}
	if _, ok := sc.mutation.EnableAutoSell(); !ok {
		return &ValidationError{Name: "enableAutoSell", err: errors.New(`ent: missing required field "Strategy.enableAutoSell"`)}
	}
	if _, ok := sc.mutation.EnableAutoExit(); !ok {
		return &ValidationError{Name: "enableAutoExit", err: errors.New(`ent: missing required field "Strategy.enableAutoExit"`)}
	}
	if _, ok := sc.mutation.EnablePushNotification(); !ok {
		return &ValidationError{Name: "enablePushNotification", err: errors.New(`ent: missing required field "Strategy.enablePushNotification"`)}
	}
	if _, ok := sc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Strategy.status"`)}
	}
	if v, ok := sc.mutation.Status(); ok {
		if err := strategy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Strategy.status": %w`, err)}
		}
	}
	return nil
}

func (sc *StrategyCreate) sqlSave(ctx context.Context) (*Strategy, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StrategyCreate) createSpec() (*Strategy, *sqlgraph.CreateSpec) {
	var (
		_node = &Strategy{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(strategy.Table, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.CreateTime(); ok {
		_spec.SetField(strategy.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := sc.mutation.UpdateTime(); ok {
		_spec.SetField(strategy.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := sc.mutation.GUID(); ok {
		_spec.SetField(strategy.FieldGUID, field.TypeString, value)
		_node.GUID = value
	}
	if value, ok := sc.mutation.UserId(); ok {
		_spec.SetField(strategy.FieldUserId, field.TypeInt64, value)
		_node.UserId = value
	}
	if value, ok := sc.mutation.Token(); ok {
		_spec.SetField(strategy.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := sc.mutation.Symbol(); ok {
		_spec.SetField(strategy.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := sc.mutation.MartinFactor(); ok {
		_spec.SetField(strategy.FieldMartinFactor, field.TypeFloat64, value)
		_node.MartinFactor = value
	}
	if value, ok := sc.mutation.MaxGridLimit(); ok {
		_spec.SetField(strategy.FieldMaxGridLimit, field.TypeInt, value)
		_node.MaxGridLimit = &value
	}
	if value, ok := sc.mutation.TakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldTakeProfitRatio, field.TypeString, value)
		_node.TakeProfitRatio = value
	}
	if value, ok := sc.mutation.UpperPriceBound(); ok {
		_spec.SetField(strategy.FieldUpperPriceBound, field.TypeString, value)
		_node.UpperPriceBound = value
	}
	if value, ok := sc.mutation.LowerPriceBound(); ok {
		_spec.SetField(strategy.FieldLowerPriceBound, field.TypeString, value)
		_node.LowerPriceBound = value
	}
	if value, ok := sc.mutation.InitialOrderSize(); ok {
		_spec.SetField(strategy.FieldInitialOrderSize, field.TypeString, value)
		_node.InitialOrderSize = value
	}
	if value, ok := sc.mutation.LastKlineVolume(); ok {
		_spec.SetField(strategy.FieldLastKlineVolume, field.TypeString, value)
		_node.LastKlineVolume = &value
	}
	if value, ok := sc.mutation.FiveKlineVolume(); ok {
		_spec.SetField(strategy.FieldFiveKlineVolume, field.TypeString, value)
		_node.FiveKlineVolume = &value
	}
	if value, ok := sc.mutation.FirstOrderId(); ok {
		_spec.SetField(strategy.FieldFirstOrderId, field.TypeInt, value)
		_node.FirstOrderId = &value
	}
	if value, ok := sc.mutation.UpperBoundExit(); ok {
		_spec.SetField(strategy.FieldUpperBoundExit, field.TypeString, value)
		_node.UpperBoundExit = &value
	}
	if value, ok := sc.mutation.StopLossExit(); ok {
		_spec.SetField(strategy.FieldStopLossExit, field.TypeString, value)
		_node.StopLossExit = &value
	}
	if value, ok := sc.mutation.TakeProfitExit(); ok {
		_spec.SetField(strategy.FieldTakeProfitExit, field.TypeString, value)
		_node.TakeProfitExit = &value
	}
	if value, ok := sc.mutation.GlobalTakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldGlobalTakeProfitRatio, field.TypeString, value)
		_node.GlobalTakeProfitRatio = &value
	}
	if value, ok := sc.mutation.DynamicStopLoss(); ok {
		_spec.SetField(strategy.FieldDynamicStopLoss, field.TypeBool, value)
		_node.DynamicStopLoss = value
	}
	if value, ok := sc.mutation.DropOn(); ok {
		_spec.SetField(strategy.FieldDropOn, field.TypeBool, value)
		_node.DropOn = value
	}
	if value, ok := sc.mutation.CandlesToCheck(); ok {
		_spec.SetField(strategy.FieldCandlesToCheck, field.TypeInt, value)
		_node.CandlesToCheck = value
	}
	if value, ok := sc.mutation.DropThreshold(); ok {
		_spec.SetField(strategy.FieldDropThreshold, field.TypeString, value)
		_node.DropThreshold = &value
	}
	if value, ok := sc.mutation.EnableAutoBuy(); ok {
		_spec.SetField(strategy.FieldEnableAutoBuy, field.TypeBool, value)
		_node.EnableAutoBuy = value
	}
	if value, ok := sc.mutation.EnableAutoSell(); ok {
		_spec.SetField(strategy.FieldEnableAutoSell, field.TypeBool, value)
		_node.EnableAutoSell = value
	}
	if value, ok := sc.mutation.EnableAutoExit(); ok {
		_spec.SetField(strategy.FieldEnableAutoExit, field.TypeBool, value)
		_node.EnableAutoExit = value
	}
	if value, ok := sc.mutation.EnablePushNotification(); ok {
		_spec.SetField(strategy.FieldEnablePushNotification, field.TypeBool, value)
		_node.EnablePushNotification = value
	}
	if value, ok := sc.mutation.Status(); ok {
		_spec.SetField(strategy.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := sc.mutation.GridTrend(); ok {
		_spec.SetField(strategy.FieldGridTrend, field.TypeString, value)
		_node.GridTrend = &value
	}
	if value, ok := sc.mutation.LastLowerThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime, value)
		_node.LastLowerThresholdAlertTime = &value
	}
	if value, ok := sc.mutation.LastUpperThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime, value)
		_node.LastUpperThresholdAlertTime = &value
	}
	return _node, _spec
}

// StrategyCreateBulk is the builder for creating many Strategy entities in bulk.
type StrategyCreateBulk struct {
	config
	err      error
	builders []*StrategyCreate
}

// Save creates the Strategy entities in the database.
func (scb *StrategyCreateBulk) Save(ctx context.Context) ([]*Strategy, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Strategy, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StrategyCreateBulk) SaveX(ctx context.Context) []*Strategy {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StrategyCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
