// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/sol-grid-bot/internal/ent/predicate"
	"github.com/fachebot/sol-grid-bot/internal/ent/wallet"
)

// WalletUpdate is the builder for updating Wallet entities.
type WalletUpdate struct {
	config
	hooks    []Hook
	mutation *WalletMutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (wu *WalletUpdate) Where(ps ...predicate.Wallet) *WalletUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUpdateTime sets the "update_time" field.
func (wu *WalletUpdate) SetUpdateTime(t time.Time) *WalletUpdate {
	wu.mutation.SetUpdateTime(t)
	return wu
}

// SetUserId sets the "userId" field.
func (wu *WalletUpdate) SetUserId(i int64) *WalletUpdate {
	wu.mutation.ResetUserId()
	wu.mutation.SetUserId(i)
	return wu
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableUserId(i *int64) *WalletUpdate {
	if i != nil {
		wu.SetUserId(*i)
	}
	return wu
}

// AddUserId adds i to the "userId" field.
func (wu *WalletUpdate) AddUserId(i int64) *WalletUpdate {
	wu.mutation.AddUserId(i)
	return wu
}

// SetAccount sets the "account" field.
func (wu *WalletUpdate) SetAccount(s string) *WalletUpdate {
	wu.mutation.SetAccount(s)
	return wu
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableAccount(s *string) *WalletUpdate {
	if s != nil {
		wu.SetAccount(*s)
	}
	return wu
}

// SetPassword sets the "password" field.
func (wu *WalletUpdate) SetPassword(s string) *WalletUpdate {
	wu.mutation.SetPassword(s)
	return wu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (wu *WalletUpdate) SetNillablePassword(s *string) *WalletUpdate {
	if s != nil {
		wu.SetPassword(*s)
	}
	return wu
}

// SetPrivateKey sets the "privateKey" field.
func (wu *WalletUpdate) SetPrivateKey(s string) *WalletUpdate {
	wu.mutation.SetPrivateKey(s)
	return wu
}

// SetNillablePrivateKey sets the "privateKey" field if the given value is not nil.
func (wu *WalletUpdate) SetNillablePrivateKey(s *string) *WalletUpdate {
	if s != nil {
		wu.SetPrivateKey(*s)
	}
	return wu
}

// Mutation returns the WalletMutation object of the builder.
func (wu *WalletUpdate) Mutation() *WalletMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WalletUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WalletUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WalletUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WalletUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WalletUpdate) defaults() {
	if _, ok := wu.mutation.UpdateTime(); !ok {
		v := wallet.UpdateDefaultUpdateTime()
		wu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WalletUpdate) check() error {
	if v, ok := wu.mutation.Account(); ok {
		if err := wallet.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Wallet.account": %w`, err)}
		}
	}
	if v, ok := wu.mutation.Password(); ok {
		if err := wallet.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Wallet.password": %w`, err)}
		}
	}
	if v, ok := wu.mutation.PrivateKey(); ok {
		if err := wallet.PrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "privateKey", err: fmt.Errorf(`ent: validator failed for field "Wallet.privateKey": %w`, err)}
		}
	}
	return nil
}

func (wu *WalletUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.UpdateTime(); ok {
		_spec.SetField(wallet.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := wu.mutation.UserId(); ok {
		_spec.SetField(wallet.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedUserId(); ok {
		_spec.AddField(wallet.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.Account(); ok {
		_spec.SetField(wallet.FieldAccount, field.TypeString, value)
	}
	if value, ok := wu.mutation.Password(); ok {
		_spec.SetField(wallet.FieldPassword, field.TypeString, value)
	}
	if value, ok := wu.mutation.PrivateKey(); ok {
		_spec.SetField(wallet.FieldPrivateKey, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WalletUpdateOne is the builder for updating a single Wallet entity.
type WalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletMutation
}

// SetUpdateTime sets the "update_time" field.
func (wuo *WalletUpdateOne) SetUpdateTime(t time.Time) *WalletUpdateOne {
	wuo.mutation.SetUpdateTime(t)
	return wuo
}

// SetUserId sets the "userId" field.
func (wuo *WalletUpdateOne) SetUserId(i int64) *WalletUpdateOne {
	wuo.mutation.ResetUserId()
	wuo.mutation.SetUserId(i)
	return wuo
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableUserId(i *int64) *WalletUpdateOne {
	if i != nil {
		wuo.SetUserId(*i)
	}
	return wuo
}

// AddUserId adds i to the "userId" field.
func (wuo *WalletUpdateOne) AddUserId(i int64) *WalletUpdateOne {
	wuo.mutation.AddUserId(i)
	return wuo
}

// SetAccount sets the "account" field.
func (wuo *WalletUpdateOne) SetAccount(s string) *WalletUpdateOne {
	wuo.mutation.SetAccount(s)
	return wuo
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableAccount(s *string) *WalletUpdateOne {
	if s != nil {
		wuo.SetAccount(*s)
	}
	return wuo
}

// SetPassword sets the "password" field.
func (wuo *WalletUpdateOne) SetPassword(s string) *WalletUpdateOne {
	wuo.mutation.SetPassword(s)
	return wuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillablePassword(s *string) *WalletUpdateOne {
	if s != nil {
		wuo.SetPassword(*s)
	}
	return wuo
}

// SetPrivateKey sets the "privateKey" field.
func (wuo *WalletUpdateOne) SetPrivateKey(s string) *WalletUpdateOne {
	wuo.mutation.SetPrivateKey(s)
	return wuo
}

// SetNillablePrivateKey sets the "privateKey" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillablePrivateKey(s *string) *WalletUpdateOne {
	if s != nil {
		wuo.SetPrivateKey(*s)
	}
	return wuo
}

// Mutation returns the WalletMutation object of the builder.
func (wuo *WalletUpdateOne) Mutation() *WalletMutation {
	return wuo.mutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (wuo *WalletUpdateOne) Where(ps ...predicate.Wallet) *WalletUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WalletUpdateOne) Select(field string, fields ...string) *WalletUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Wallet entity.
func (wuo *WalletUpdateOne) Save(ctx context.Context) (*Wallet, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WalletUpdateOne) SaveX(ctx context.Context) *Wallet {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WalletUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WalletUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WalletUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdateTime(); !ok {
		v := wallet.UpdateDefaultUpdateTime()
		wuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WalletUpdateOne) check() error {
	if v, ok := wuo.mutation.Account(); ok {
		if err := wallet.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Wallet.account": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.Password(); ok {
		if err := wallet.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Wallet.password": %w`, err)}
		}
	}
	if v, ok := wuo.mutation.PrivateKey(); ok {
		if err := wallet.PrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "privateKey", err: fmt.Errorf(`ent: validator failed for field "Wallet.privateKey": %w`, err)}
		}
	}
	return nil
}

func (wuo *WalletUpdateOne) sqlSave(ctx context.Context) (_node *Wallet, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Wallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallet.FieldID)
		for _, f := range fields {
			if !wallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.UpdateTime(); ok {
		_spec.SetField(wallet.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.UserId(); ok {
		_spec.SetField(wallet.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedUserId(); ok {
		_spec.AddField(wallet.FieldUserId, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.Account(); ok {
		_spec.SetField(wallet.FieldAccount, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Password(); ok {
		_spec.SetField(wallet.FieldPassword, field.TypeString, value)
	}
	if value, ok := wuo.mutation.PrivateKey(); ok {
		_spec.SetField(wallet.FieldPrivateKey, field.TypeString, value)
	}
	_node = &Wallet{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
