// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Grid is the predicate function for grid builders.
type Grid func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// Strategy is the predicate function for strategy builders.
type Strategy func(*sql.Selector)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
